In [1]:
import json
import pandas as pd
from tqdm import tqdm

from graphs.legal_mcq_graph import run_mcq

In [2]:
QUESTIONS_PATH = r"F:\Thesis\project\403-vekalat\structured_questions.csv"
GOLD_PATH      = r"F:\Thesis\project\1-BaselineTest\GOLD\Gold.csv"

df_q = pd.read_csv(QUESTIONS_PATH)
df_gold = pd.read_csv(GOLD_PATH)

print("Questions:", len(df_q))
print("Gold:", len(df_gold))

display(df_q.head(2))
display(df_gold.head(2))

Questions: 119
Gold: 119

,question_number,category,question,options
0,1,حقوق مدنی,کدام یک از موارد زیر صحیح است؟,1) با توافق طرفین امکان از بین بردن سبب انفساخ...
1,2,حقوق مدنی,شخص «الف» حین رانندگی با خودرو سواری با شخص «ب...,1) دیه هر دو راننده صرفاً تا میزان دیه کامل و ...

   idx Gold
0    1    3
1    2    2

In [3]:
# حذف سوال 89
if 89 in df_gold["idx"].values:
    df_gold = df_gold[df_gold["idx"] != 89].reset_index(drop=True)

multi_gold = {
    90: ["3", "4"],
    53: ["1", "2"],
    52: ["2", "4"],
    48: ["1", "3"],
    46: ["1", "3"],
    36: ["1", "4"],
    30: ["1", "2"],
    25: ["3", "4"],
    9:  ["1", "2"],
    4:  ["1", "4"],
    3:  ["2", "4"],
}

def normalize_gold_value(idx: int, gold_val: str) -> str:
    if idx in multi_gold:
        return ",".join(multi_gold[idx])

    val = str(gold_val).strip()
    digits = [ch for ch in val if ch.isdigit()]
    if not digits:
        return val
    if len(digits) == 1:
        return digits[0]
    return ",".join(digits)

df_gold["Gold"] = [
    normalize_gold_value(int(idx), gold)
    for idx, gold in zip(df_gold["idx"], df_gold["Gold"])
]

display(df_gold.head(5))

   idx Gold
0    1    3
1    2    2
2    3  2,4
3    4  1,4
4    5    3

In [4]:
def is_correct(pred: str, gold: str) -> bool:
    gold_set = {g.strip() for g in str(gold).split(",") if g.strip()}
    return str(pred).strip() in gold_set

In [5]:
subset = df_q.copy()

# مثال: فقط چند سوال خاص
# subset = df_q[df_q["question_number"].isin([3,4,5,25,30,36,46,48,52,53,90])]

print("Subset size:", len(subset))

Subset size: 119

In [6]:
results_rows = []

for _, row in tqdm(subset.iterrows(), total=len(subset)):
    q_num = int(row["question_number"])
    category = str(row["category"]).strip()
    question = str(row["question"]).strip()
    options_raw = row["options"]

    gold_row = df_gold[df_gold["idx"] == q_num]
    gold_val = gold_row["Gold"].iloc[0] if not gold_row.empty else None

    # اجرای گراف از طریق helper
    out = run_mcq(
        question_number=q_num,
        category=category,
        question=question,
        options_raw=options_raw,
        max_revisions=2,
    )

    final_toon = out.get("final_toon") or {}
    pred_answer = final_toon.get("answer")
    confidence = final_toon.get("confidence")
    explanation = final_toon.get("explanation")

    critic_toon = out.get("critic_toon") or {}
    needs_revision = critic_toon.get("needs_revision")
    critic_issue = critic_toon.get("issue")
    critic_action = critic_toon.get("action")

    correct = None
    if gold_val is not None and pred_answer is not None:
        correct = is_correct(pred_answer, gold_val)

    results_rows.append({
        "question_number": q_num,
        "category": category,
        "gold": gold_val,
        "pred": pred_answer,
        "is_correct": correct,
        "confidence": confidence,
        "needs_revision": needs_revision,
        "critic_issue": critic_issue,
        "critic_action": critic_action,
        # برای خطایابی سریع:
        "context_preview": out.get("context_preview"),
        "docs_meta": out.get("docs_meta"),
    })

  0%|          | 0/119 [00:00<?, ?it/s]

📝 Query: کدام یک از موارد زیر صحیح است؟...
🔍 روش انتخاب شده: Semantic search
🔍 Semantic only: 20 نتیجه
   ✓ Retrieved: 20 documents
🔄 Reranking 20 سند (بدون law+article)...
   ✓ Reranked: top 5 documents

  1%|          | 1/119 [00:20<41:12, 20.95s/it]

📝 Query: شخص «الف» حین رانندگی با خودرو سواری با شخص «ب» (موتورسوار) تصادف می کند شخص «ال...
🎯 روش انتخاب شده: Metadata-aware
🎯 Metadata: law='قانون بیمه اجباری خسارات وارد شده به شخص ثالث در اثر حوادث ناشی از وسایل نقلیه' | None None
🔍 فیلتر فقط قانون...
   ✓ 0 سند (law_only)
🔍 Semantic fallback...
✅ نهایی: 20 نتیجه
   ✓ Retrieved: 20 documents
🔄 Reranking 20 سند (بدون law+article)...
   ✓ Reranked: top 5 documents

  2%|▏         | 2/119 [00:59<1:00:29, 31.02s/it]

📝 Query: کدام مورد در خصوص تصرفی که همراه با قصد تملک باشد صحیح است؟...
🔍 روش انتخاب شده: Semantic search
🔍 Semantic only: 20 نتیجه
   ✓ Retrieved: 20 documents
🔄 Reranking 20 سند (بدون law+article)...
   ✓ Reranked: top 5 documents

  3%|▎         | 3/119 [01:10<42:24, 21.94s/it]

📝 Query: شخص «الف» (جراح پلاستیک زیبایی) که تحت پوشش کامل بیمه مسئولیت مدنی ناشی از تقصیر...
🎯 روش انتخاب شده: Metadata-aware
🎯 Metadata: law='قانون مسئولیت مدنی' | None None
🔍 فیلتر فقط قانون...
   ✓ 10 سند (law_only)
🔍 Semantic fallback...
✅ نهایی: 20 نتیجه
   ✓ Retrieved: 20 documents
🔄 Reranking 20 سند (بدون law+article)...
   ✓ Reranked: top 5 documents

  3%|▎         | 4/119 [01:25<37:01, 19.31s/it]

📝 Query: شرط وکالت زن در طلاق در چه قالب هایی قابل تحقق است؟...
🔍 روش انتخاب شده: Semantic search
🔍 Semantic only: 20 نتیجه
   ✓ Retrieved: 20 documents
🔄 Reranking 20 سند (بدون law+article)...
   ✓ Reranked: top 5 documents

  4%|▍         | 5/119 [01:39<33:11, 17.47s/it]

📝 Query: کدام مورد در خصوص تشابه »هبه« و »وصیت تملیکی«، صحیح است؟...
🔍 روش انتخاب شده: Semantic search
🔍 Semantic only: 20 نتیجه
   ✓ Retrieved: 20 documents
🔄 Reranking 20 سند (بدون law+article)...
   ✓ Reranked: top 5 documents

  5%|▌         | 6/119 [02:04<37:52, 20.11s/it]

📝 Query: مسئولیت کدام یک از اشخاص زیر در مقابل متعهدله یا زیان دیده به تسهیم است نه تضامن...
🔍 روش انتخاب شده: Semantic search
🔍 Semantic only: 20 نتیجه
   ✓ Retrieved: 20 documents
🔄 Reranking 20 سند (بدون law+article)...
   ✓ Reranked: top 5 documents

  6%|▌         | 7/119 [02:36<44:18, 23.74s/it]

📝 Query: در قرارداد فروش مالی شرط می شود که چنانچه ثمن معامله ظرف مدت یک ماه پرداخت نشود ...
🔍 روش انتخاب شده: Semantic search
🔍 Semantic only: 20 نتیجه
   ✓ Retrieved: 20 documents
🔄 Reranking 20 سند (بدون law+article)...
   ✓ Reranked: top 5 documents

  7%|▋         | 8/119 [03:06<48:06, 26.01s/it]

📝 Query: چنانچه مسئولیت مدنی مبتنی بر تقصیر باشد کدام یک از اشخاص زیر در برابر زیان دیده ...
🎯 روش انتخاب شده: Metadata-aware
🎯 Metadata: law='قانون مسئولیت مدنی' | None None
🔍 فیلتر فقط قانون...
   ✓ 10 سند (law_only)
🔍 Semantic fallback...
✅ نهایی: 20 نتیجه
   ✓ Retrieved: 20 documents
🔄 Reranking 20 سند (بدون law+article)...
   ✓ Reranked: top 5 documents

  8%|▊         | 9/119 [03:20<40:17, 21.98s/it]

📝 Query: پدر برای اداره اموال فرزندان صغیرش بعد از فوت خود برادرش را به عنوان وصی تعیین م...
🔍 روش انتخاب شده: Semantic search
🔍 Semantic only: 20 نتیجه
   ✓ Retrieved: 20 documents
🔄 Reranking 20 سند (بدون law+article)...
   ✓ Reranked: top 5 documents

  8%|▊         | 10/119 [03:45<41:37, 22.91s/it]

📝 Query: کدام مورد در خصوص تشابه و تفاوت تعلیق در مرحله انعقاد قرارداد و تعلیق در مرحله ا...
🔍 روش انتخاب شده: Semantic search
🔍 Semantic only: 20 نتیجه
   ✓ Retrieved: 20 documents
🔄 Reranking 20 سند (بدون law+article)...
   ✓ Reranked: top 5 documents

  9%|▉         | 11/119 [04:05<40:01, 22.24s/it]

📝 Query: أجل برای انجام تعهدات قراردادی ناشی از کدام یک از موارد زیر می تواند باشد؟...
🔍 روش انتخاب شده: Semantic search
🔍 Semantic only: 20 نتیجه
   ✓ Retrieved: 20 documents
🔄 Reranking 20 سند (بدون law+article)...
   ✓ Reranked: top 5 documents

 10%|█         | 12/119 [04:30<41:09, 23.08s/it]

📝 Query: کدام مورد در خصوص تفاوت و تشابه عقد و ایقاع صحیح نیست ؟...
🔍 روش انتخاب شده: Semantic search
🔍 Semantic only: 20 نتیجه
   ✓ Retrieved: 20 documents
🔄 Reranking 20 سند (بدون law+article)...
   ✓ Reranked: top 5 documents

 11%|█         | 13/119 [05:01<44:38, 25.27s/it]

📝 Query: با توجه به قانون روابط موجر و مستأجر 1376 کدام مورد صحیح است؟...
🎯 روش انتخاب شده: Metadata-aware
🎯 Metadata: law='قانون روابط موجر و مستاجر مصوب 1356' | None None
🔍 فیلتر فقط قانون...
   ✓ 0 سند (law_only)
🔍 Semantic fallback...
✅ نهایی: 20 نتیجه
   ✓ Retrieved: 20 documents
🔄 Reranking 20 سند (بدون law+article)...
   ✓ Reranked: top 5 documents

 12%|█▏        | 14/119 [05:20<41:16, 23.59s/it]

📝 Query: کدام مورد در خصوص حقوق پدیدآورندگان آثار، صحیح نیست؟...
🔍 روش انتخاب شده: Semantic search
🔍 Semantic only: 20 نتیجه
   ✓ Retrieved: 20 documents
🔄 Reranking 20 سند (بدون law+article)...
   ✓ Reranked: top 5 documents

 13%|█▎        | 15/119 [05:47<42:18, 24.41s/it]

📝 Query: « الف» به عنوان وکیل »ب« ملک »ب« را به یک سوم قیمت عرفی به «ج» واگذار می کند. با...
🔍 روش انتخاب شده: Semantic search
🔍 Semantic only: 20 نتیجه
   ✓ Retrieved: 20 documents
🔄 Reranking 20 سند (بدون law+article)...
   ✓ Reranked: top 5 documents

 13%|█▎        | 16/119 [06:01<36:30, 21.27s/it]

📝 Query: کدام مورد در خصوص رد ترکه، صحیح است؟...
🔍 روش انتخاب شده: Semantic search
🔍 Semantic only: 20 نتیجه
   ✓ Retrieved: 20 documents
🔄 Reranking 20 سند (بدون law+article)...
   ✓ Reranked: top 5 documents

 14%|█▍        | 17/119 [06:38<44:24, 26.12s/it]

📝 Query: شخصی فوت می کند که حین الفوت همسرش باردار بوده و پدر و مادرش در قید حیات نیستند ...
🔍 روش انتخاب شده: Semantic search
🔍 Semantic only: 20 نتیجه
   ✓ Retrieved: 20 documents
🔄 Reranking 20 سند (بدون law+article)...
   ✓ Reranked: top 5 documents

 15%|█▌        | 18/119 [07:31<57:27, 34.14s/it]

📝 Query: عین معین متعلق به متعهدله نزد متعهد است، متعهد به جای آن مال، مال دیگری به متعهد...
🔍 روش انتخاب شده: Semantic search
🔍 Semantic only: 20 نتیجه
   ✓ Retrieved: 20 documents
🔄 Reranking 20 سند (بدون law+article)...
   ✓ Reranked: top 5 documents

 16%|█▌        | 19/119 [07:40<44:36, 26.76s/it]

📝 Query: آیا مستعیر می تواند از جهت تعهد به حفاظت و اداره مال، مال عاریه را به تصرف غیر د...
🔍 روش انتخاب شده: Semantic search
🔍 Semantic only: 20 نتیجه
   ✓ Retrieved: 20 documents
🔄 Reranking 20 سند (بدون law+article)...
   ✓ Reranked: top 5 documents

 17%|█▋        | 20/119 [07:52<36:51, 22.34s/it]

📝 Query: چنانچه آیین نامه دولتی با صدور رأی هیئت عمومی دیوان عدالت اداری ابطال شود، در خص...
🎯 روش انتخاب شده: Metadata-aware
🎯 Metadata: law='قانون دیوان عدالت اداری' | None None
🔍 فیلتر فقط قانون...
   ✓ 10 سند (law_only)
🔍 Semantic fallback...
✅ نهایی: 20 نتیجه
   ✓ Retrieved: 20 documents
🔄 Reranking 20 سند (بدون law+article)...
   ✓ Reranked: top 5 documents

 18%|█▊        | 21/119 [08:01<29:55, 18.32s/it]

📝 Query: دو شخص که اختلاف خود را برای فصل، به سه نفر داور ارجاع دادهاند. پس از ارجاع به د...
🔍 روش انتخاب شده: Semantic search
🔍 Semantic only: 20 نتیجه
   ✓ Retrieved: 20 documents
🔄 Reranking 20 سند (بدون law+article)...
   ✓ Reranked: top 5 documents

 18%|█▊        | 22/119 [08:13<26:22, 16.32s/it]

📝 Query: حکمی در تأیید حکم دادگاه نخستین از دادگاه تجدیدنظر استان صادر و در مهلت مقرر از ...
🔍 روش انتخاب شده: Semantic search
🔍 Semantic only: 20 نتیجه
   ✓ Retrieved: 20 documents
🔄 Reranking 20 سند (بدون law+article)...
   ✓ Reranked: top 5 documents

 19%|█▉        | 23/119 [08:33<27:57, 17.47s/it]

📝 Query: حکمی قطعی از دادگاه تجدید نظر استان، له شخص «الف» با وکالت شخص «ج» علیه شخص «ب» ...
🔍 روش انتخاب شده: Semantic search
🔍 Semantic only: 20 نتیجه
   ✓ Retrieved: 20 documents
🔄 Reranking 20 سند (بدون law+article)...
   ✓ Reranked: top 5 documents

 20%|██        | 24/119 [09:14<38:43, 24.45s/it]

📝 Query: در خصوص رعایت اصول و تشریفات دادرسی در رسیدگی به امور حقوقی با توجه به قانون شور...
🎯 روش انتخاب شده: Metadata-aware
🎯 Metadata: law='قانون شوراهای حل اختلاف' | None None
🔍 فیلتر فقط قانون...
   ✓ 10 سند (law_only)
🔍 Semantic fallback...
✅ نهایی: 20 نتیجه
   ✓ Retrieved: 20 documents
🔄 Reranking 20 سند (بدون law+article)...
   ✓ Reranked: top 5 documents

 21%|██        | 25/119 [09:32<35:23, 22.59s/it]

📝 Query: با توجه به قانون شوراهای حل اختلاف مصوب 1402 و قانون تشکیل دادگاههای خانواده تحر...
🎯 روش انتخاب شده: Metadata-aware
🎯 Metadata: law='قانون شوراهای حل اختلاف' | None None
🔍 فیلتر فقط قانون...
   ✓ 10 سند (law_only)
🔍 Semantic fallback...
✅ نهایی: 20 نتیجه
   ✓ Retrieved: 20 documents
🔄 Reranking 20 سند (بدون law+article)...
   ✓ Reranked: top 5 documents

 22%|██▏       | 26/119 [09:54<34:37, 22.34s/it]

📝 Query: داد خواستی در دیوان عدالت اداری مطرح شده که شاکیان آن پنج نفر می باشند. در خصوص ...
🎯 روش انتخاب شده: Metadata-aware
🎯 Metadata: law='قانون دیوان عدالت اداری' | None None
🔍 فیلتر فقط قانون...
   ✓ 10 سند (law_only)
🔍 Semantic fallback...
✅ نهایی: 20 نتیجه
   ✓ Retrieved: 20 documents
🔄 Reranking 20 سند (بدون law+article)...
   ✓ Reranked: top 5 documents

 23%|██▎       | 27/119 [10:11<31:47, 20.74s/it]

📝 Query: سندی در خارج از کشور تنظیم شده و نماینده کنسولی موافقت آن را با قوانین کشور محل ...
🔍 روش انتخاب شده: Semantic search
🔍 Semantic only: 20 نتیجه
   ✓ Retrieved: 20 documents
🔄 Reranking 20 سند (بدون law+article)...
   ✓ Reranked: top 5 documents

 24%|██▎       | 28/119 [10:28<29:36, 19.52s/it]

📝 Query: در خصوص مهلت اعتراض به نظریه کارشناسی در پرونده دادرسی و ارزیاب در اجرای احکام م...
🎯 روش انتخاب شده: Metadata-aware
🎯 Metadata: law='قانون اجرای احکام مدنی' | None None
🔍 فیلتر فقط قانون...
   ✓ 10 سند (law_only)
🔍 Semantic fallback...
✅ نهایی: 20 نتیجه
   ✓ Retrieved: 20 documents
🔄 Reranking 20 سند (بدون law+article)...
   ✓ Reranked: top 5 documents

 24%|██▍       | 29/119 [10:56<33:15, 22.18s/it]

📝 Query: در خصوص قابلیت فرجام احکام صادره از دادگاه تجدید نظر راجع به متفرعات دعوی که ضمن...
🎯 روش انتخاب شده: Metadata-aware
🎯 Metadata: law='None' | اصل نکاح
🔍 Semantic fallback...
✅ نهایی: 20 نتیجه
   ✓ Retrieved: 20 documents
🔄 Reranking 20 سند (بدون law+article)...
   ✓ Reranked: top 5 documents

 25%|██▌       | 30/119 [11:15<31:36, 21.30s/it]

📝 Query: در دعوایی که به خواسته پرداخت ده میلیارد ریال علیه شخص «الف» و شخص «ب» اقامه شده...
🔍 روش انتخاب شده: Semantic search
🔍 Semantic only: 20 نتیجه
   ✓ Retrieved: 20 documents
🔄 Reranking 20 سند (بدون law+article)...
   ✓ Reranked: top 5 documents

 26%|██▌       | 31/119 [11:44<34:43, 23.68s/it]

📝 Query: حکم خلع ید از یک باب ویلا، له شخص «الف» و علیه شخص «ب» صادر، قطعی و اجرا می شود....
🔍 روش انتخاب شده: Semantic search
🔍 Semantic only: 20 نتیجه
   ✓ Retrieved: 20 documents
🔄 Reranking 20 سند (بدون law+article)...
   ✓ Reranked: top 5 documents

 27%|██▋       | 32/119 [12:19<39:07, 26.99s/it]

📝 Query: چنانچه هر یک از اصحاب دعوی اصول استاد عادی را که رو گرفت آنها را ارائه کرده اند ...
🔍 روش انتخاب شده: Semantic search
🔍 Semantic only: 20 نتیجه
   ✓ Retrieved: 20 documents
🔄 Reranking 20 سند (بدون law+article)...
   ✓ Reranked: top 5 documents

 28%|██▊       | 33/119 [12:41<36:39, 25.57s/it]

📝 Query: در خصوص بازداشت یک حلقه انگشتری گران قیمت، کدام مورد صحیح است؟...
🔍 روش انتخاب شده: Semantic search
🔍 Semantic only: 20 نتیجه
   ✓ Retrieved: 20 documents
🔄 Reranking 20 سند (بدون law+article)...
   ✓ Reranked: top 5 documents

 29%|██▊       | 34/119 [12:57<32:02, 22.61s/it]

📝 Query: خوانده دعوی برای اثبات ادعای خود مبنی بر مطالبه وجه نقد، دو گواه معرفی می کند دا...
🔍 روش انتخاب شده: Semantic search
🔍 Semantic only: 20 نتیجه
   ✓ Retrieved: 20 documents
🔄 Reranking 20 سند (بدون law+article)...
   ✓ Reranked: top 5 documents

 29%|██▉       | 35/119 [13:11<28:02, 20.03s/it]

📝 Query: در دعوایی که خواسته آن چهل میلیون ریال تقویم شده است، حکمی از دادگاه صلح صادر و ...
🔍 روش انتخاب شده: Semantic search
🔍 Semantic only: 20 نتیجه
   ✓ Retrieved: 20 documents
🔄 Reranking 20 سند (بدون law+article)...
   ✓ Reranked: top 5 documents

 30%|███       | 36/119 [13:23<24:26, 17.67s/it]

📝 Query: حکمی از دادگاه تجدیدنظر استان صادر و قطعی شده و عملیات اجرایی حکم در حال انجام ا...
🔍 روش انتخاب شده: Semantic search
🔍 Semantic only: 20 نتیجه
   ✓ Retrieved: 20 documents
🔄 Reranking 20 سند (بدون law+article)...
   ✓ Reranked: top 5 documents

 31%|███       | 37/119 [14:11<36:22, 26.61s/it]

📝 Query: چنانچه خواهان در بخش هزینه دادرسی دادخواست ناقص تقدیم کند و در پی اخطار رفع نقص ...
🔍 روش انتخاب شده: Semantic search
🔍 Semantic only: 20 نتیجه
   ✓ Retrieved: 20 documents
🔄 Reranking 20 سند (بدون law+article)...
   ✓ Reranked: top 5 documents

 32%|███▏      | 38/119 [14:22<29:32, 21.88s/it]

📝 Query: چنانچه میان دادگاه عمومی حقوقی و دادگاه کیفری دو از یک استان اختلاف در صلاحیت رخ...
🔍 روش انتخاب شده: Semantic search
🔍 Semantic only: 20 نتیجه
   ✓ Retrieved: 20 documents
🔄 Reranking 20 سند (بدون law+article)...
   ✓ Reranked: top 5 documents

 33%|███▎      | 39/119 [14:34<25:33, 19.16s/it]

📝 Query: دعوایی علیه سه نفر به اسامی شخص «الف» و شخص «ب» و شخص «ج» به خواسته 30 میلیارد ر...
🎯 روش انتخاب شده: Metadata-aware
🎯 Metadata: law='None' | اصل نمی شود
🔍 Semantic fallback...
✅ نهایی: 20 نتیجه
   ✓ Retrieved: 20 documents
🔄 Reranking 20 سند (بدون law+article)...
   ✓ Reranked: top 5 documents

 34%|███▎      | 40/119 [15:07<30:23, 23.08s/it]

📝 Query: ضمانت اجرای عدم مطالبه باقیمانده مبلغ اسمی سهام در شرکت سهامی از سوی مدیران شرکت...
🔍 روش انتخاب شده: Semantic search
🔍 Semantic only: 20 نتیجه
   ✓ Retrieved: 20 documents
🔄 Reranking 20 سند (بدون law+article)...
   ✓ Reranked: top 5 documents

 34%|███▍      | 41/119 [15:31<30:22, 23.36s/it]

📝 Query: در خصوص انتخاب یک شخص اصالتاً یا به نمایندگی از شخص حقوقی در ترکیب هیئت مدیره چن...
🔍 روش انتخاب شده: Semantic search
🔍 Semantic only: 20 نتیجه
   ✓ Retrieved: 20 documents
🔄 Reranking 20 سند (بدون law+article)...
   ✓ Reranked: top 5 documents

 35%|███▌      | 42/119 [15:45<26:32, 20.68s/it]

📝 Query: اگر پس از تقسیم و خاتمه ورشکستگی مالی متعلق به ورشکسته کشف شود، تکلیف اداره تصفی...
🎯 روش انتخاب شده: Metadata-aware
🎯 Metadata: law='قانون اداره تصفیه امور ورشکستگی' | None None
🔍 فیلتر فقط قانون...
   ✓ 10 سند (law_only)
🔍 Semantic fallback...
✅ نهایی: 20 نتیجه
   ✓ Retrieved: 20 documents
🔄 Reranking 20 سند (بدون law+article)...
   ✓ Reranked: top 5 documents

 36%|███▌      | 43/119 [16:00<24:04, 19.00s/it]

📝 Query: اثر ثبت نام اشخاص در دفتر ثبت تجاری چیست؟...
🔍 روش انتخاب شده: Semantic search
🔍 Semantic only: 20 نتیجه
   ✓ Retrieved: 20 documents
🔄 Reranking 20 سند (بدون law+article)...
   ✓ Reranked: top 5 documents

 37%|███▋      | 44/119 [16:11<20:31, 16.43s/it]

📝 Query: کدام مورد در خصوص «اضافه ارزش سهام» که هنگام افزایش سرمایه شرکت سهامی دریافت می ...
🔍 روش انتخاب شده: Semantic search
🔍 Semantic only: 20 نتیجه
   ✓ Retrieved: 20 documents
🔄 Reranking 20 سند (بدون law+article)...
   ✓ Reranked: top 5 documents

 38%|███▊      | 45/119 [16:27<20:16, 16.44s/it]

📝 Query: در خصوص مسئولیت حقوقی دلالی که در نفس معامله منتفع میباشد و این موضوع را به طرف ...
🔍 روش انتخاب شده: Semantic search
🔍 Semantic only: 20 نتیجه
   ✓ Retrieved: 20 documents
🔄 Reranking 20 سند (بدون law+article)...
   ✓ Reranked: top 5 documents

 39%|███▊      | 46/119 [16:38<18:09, 14.93s/it]

📝 Query: مطابق مقررات قانون تجارت در خصوص مفقودی برات کدام یک از موارد زیر اصولاً نیازی ب...
🎯 روش انتخاب شده: Metadata-aware
🎯 Metadata: law='قانون تجارت' | None None
🔍 فیلتر فقط قانون...
   ✓ 10 سند (law_only)
🔍 Semantic fallback...
✅ نهایی: 20 نتیجه
   ✓ Retrieved: 20 documents
🔄 Reranking 20 سند (بدون law+article)...
   ✓ Reranked: top 5 documents

 39%|███▉      | 47/119 [16:55<18:21, 15.30s/it]

📝 Query: در صورتی که به موجب تصمیم مجمع عمومی عادی شخصی که کارمند رسمی دولت است به عنوان ...
🔍 روش انتخاب شده: Semantic search
🔍 Semantic only: 20 نتیجه
   ✓ Retrieved: 20 documents
🔄 Reranking 20 سند (بدون law+article)...
   ✓ Reranked: top 5 documents

 40%|████      | 48/119 [17:40<28:41, 24.24s/it]

📝 Query: در صورتی که مجمع عمومی عادی به طور فوق العاده شرکت سهامی، بازرس اصلی شرکت را بدو...
🔍 روش انتخاب شده: Semantic search
🔍 Semantic only: 20 نتیجه
   ✓ Retrieved: 20 documents
🔄 Reranking 20 سند (بدون law+article)...
   ✓ Reranked: top 5 documents

 41%|████      | 49/119 [18:03<27:52, 23.89s/it]

📝 Query: کدام مورد در خصوص تبدیل شرکت تجاری موجود به نوع دیگر در حقوق موضوعه ایران، صحیح ...
🔍 روش انتخاب شده: Semantic search
🔍 Semantic only: 20 نتیجه
   ✓ Retrieved: 20 documents
🔄 Reranking 20 سند (بدون law+article)...
   ✓ Reranked: top 5 documents

 42%|████▏     | 50/119 [18:20<25:10, 21.89s/it]

📝 Query: برای انتشار اعلامیه پذیره نویسی یک شرکت سهامی عام با سرمایه  20میلیارد ریال کدام...
🔍 روش انتخاب شده: Semantic search
🔍 Semantic only: 20 نتیجه
   ✓ Retrieved: 20 documents
🔄 Reranking 20 سند (بدون law+article)...
   ✓ Reranked: top 5 documents

 43%|████▎     | 51/119 [18:35<22:18, 19.69s/it]

📝 Query: کدام مورد در خصوص تأثیر متقابل ورشکستگی شرکت تجاری و شریک شرکت، صحیح است؟...
🔍 روش انتخاب شده: Semantic search
🔍 Semantic only: 20 نتیجه
   ✓ Retrieved: 20 documents
🔄 Reranking 20 سند (بدون law+article)...
   ✓ Reranked: top 5 documents

 44%|████▎     | 52/119 [18:45<18:46, 16.82s/it]

📝 Query: در مبایعه نامه ای شرط شده است که چک شماره فلان بابت قسط آخر ثمن معامله پس از انت...
🔍 روش انتخاب شده: Semantic search
🔍 Semantic only: 20 نتیجه
   ✓ Retrieved: 20 documents
🔄 Reranking 20 سند (بدون law+article)...
   ✓ Reranked: top 5 documents

 45%|████▍     | 53/119 [19:20<24:31, 22.29s/it]

📝 Query: کدام مورد در خصوص احکام قانونی چک صحیح نیست؟...
🔍 روش انتخاب شده: Semantic search
🔍 Semantic only: 20 نتیجه
   ✓ Retrieved: 20 documents
🔄 Reranking 20 سند (بدون law+article)...
   ✓ Reranked: top 5 documents

 45%|████▌     | 54/119 [19:40<23:35, 21.78s/it]

📝 Query: کدام مورد در خصوص چک صیادی که منجر به صدور گواهی عدم پرداخت شده صحیح نیست؟...
🔍 روش انتخاب شده: Semantic search
🔍 Semantic only: 20 نتیجه
   ✓ Retrieved: 20 documents
🔄 Reranking 20 سند (بدون law+article)...
   ✓ Reranked: top 5 documents

 46%|████▌     | 55/119 [19:57<21:27, 20.11s/it]

📝 Query: کدام مورد در خصوص حکم ورشکستگی صحیح نیست؟...
🔍 روش انتخاب شده: Semantic search
🔍 Semantic only: 20 نتیجه
   ✓ Retrieved: 20 documents
🔄 Reranking 20 سند (بدون law+article)...
   ✓ Reranked: top 5 documents

 47%|████▋     | 56/119 [20:22<22:47, 21.70s/it]

📝 Query: کدام یک از اعمال حقوقی تاجر ورشکسته پس از صدور حکم ورشکستگی نافذ نیست؟...
🔍 روش انتخاب شده: Semantic search
🔍 Semantic only: 20 نتیجه
   ✓ Retrieved: 20 documents
🔄 Reranking 20 سند (بدون law+article)...
   ✓ Reranked: top 5 documents

 48%|████▊     | 57/119 [20:52<24:54, 24.10s/it]

📝 Query: سند تجاری به مبلغ ده میلیون ریال صادر شده است و در ظهر آن مبلغ سند توسط صادر کنن...
🔍 روش انتخاب شده: Semantic search
🔍 Semantic only: 20 نتیجه
   ✓ Retrieved: 20 documents
🔄 Reranking 20 سند (بدون law+article)...
   ✓ Reranked: top 5 documents

 49%|████▊     | 58/119 [21:08<22:13, 21.86s/it]

📝 Query: کدام مورد در خصوص گواهینامه موقت سهم، صحیح است؟...
🔍 روش انتخاب شده: Semantic search
🔍 Semantic only: 20 نتیجه
   ✓ Retrieved: 20 documents
🔄 Reranking 20 سند (بدون law+article)...
   ✓ Reranked: top 5 documents

 50%|████▉     | 59/119 [21:33<22:37, 22.63s/it]

📝 Query: پس از انتشار صورت مطالبات تصدیق شده توسط اداره تصفیه طلبکاران چه اقدامی می توانن...
🎯 روش انتخاب شده: Metadata-aware
🎯 Metadata: law='قانون اداره تصفیه امور ورشکستگی' | None None
🔍 فیلتر فقط قانون...
   ✓ 10 سند (law_only)
🔍 Semantic fallback...
✅ نهایی: 20 نتیجه
   ✓ Retrieved: 20 documents
🔄 Reranking 20 سند (بدون law+article)...
   ✓ Reranked: top 5 documents

 50%|█████     | 60/119 [22:01<23:58, 24.38s/it]

📝 Query: یک فرانسوی در خاک آلمان امضای وزیر دادگستری ایران را جعل میکند و در آلمان از آن ...
🎯 روش انتخاب شده: Metadata-aware
🎯 Metadata: law='قانون مجازات استفاده کنندگان غیرمجاز از آب، برق، تلفن، فاضلاب و گاز' | None None
🔍 فیلتر فقط قانون...
   ✓ 0 سند (law_only)
🔍 Semantic fallback...
✅ نهایی: 20 نتیجه
   ✓ Retrieved: 20 documents
🔄 Reranking 20 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 51%|█████▏    | 61/119 [23:14<37:33, 38.86s/it]

📝 Query: سربازی در جبهه جنگ در حالی که در محاصره دشمن ،است برای اینکه بیسیم در اختیار وی ...
🎯 روش انتخاب شده: Metadata-aware
🎯 Metadata: law='قانون حداکثر استفاده از توان تولیدی و خدماتی کشور و حمایت از کالای ایرانی' | None None
🔍 فیلتر فقط قانون...
   ✓ 10 سند (law_only)
🔍 Semantic fallback...
✅ نهایی: 24 نتیجه
   ✓ Retrieved: 24 documents
🔄 Reranking 24 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 52%|█████▏    | 62/119 [23:26<29:13, 30.76s/it]

📝 Query: کدام جرایم زیر قابل گذشت محسوب میشوند؟...
🔍 روش انتخاب شده: Semantic search
🔍 Semantic only: 24 نتیجه
   ✓ Retrieved: 24 documents
🔄 Reranking 24 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 53%|█████▎    | 63/119 [23:47<26:06, 27.97s/it]

📝 Query: جرم غیر عمد که باعث صدمه به شخصی شده به شخصی حقوقی منتسب است. کدام مجازاتها قابل...
🎯 روش انتخاب شده: Metadata-aware
🎯 Metadata: law='قانون مجازات اعمال نفوذ برخلاف حق و مقررات قانونی' | None None
🔍 فیلتر فقط قانون...
   ✓ 0 سند (law_only)
🔍 Semantic fallback...
✅ نهایی: 20 نتیجه
   ✓ Retrieved: 20 documents
🔄 Reranking 20 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 54%|█████▍    | 64/119 [24:15<25:29, 27.80s/it]

📝 Query: کدام مورد در خصوص مجازاتهای تکمیلی و تبعی، صحیح است؟...
🔍 روش انتخاب شده: Semantic search
🔍 Semantic only: 24 نتیجه
   ✓ Retrieved: 24 documents
🔄 Reranking 24 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 55%|█████▍    | 65/119 [24:37<23:29, 26.11s/it]

📝 Query: کدام مجازات تعزیری زیر در مقام تخفیف قابل تبدیل به مجازات دیگر نیست؟...
🎯 روش انتخاب شده: Metadata-aware
🎯 Metadata: law='قانون کاهش مجازات حبس تعزیری' | None None
🔍 فیلتر فقط قانون...
   ✓ 10 سند (law_only)
🔍 Semantic fallback...
✅ نهایی: 24 نتیجه
   ✓ Retrieved: 24 documents
🔄 Reranking 24 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 55%|█████▌    | 66/119 [25:01<22:33, 25.53s/it]

📝 Query: – در صورت وجود سابقه محکومیت کیفری مؤثر فرد از کدام نهاد میتواند برخوردار شود؟...
🔍 روش انتخاب شده: Semantic search
🔍 Semantic only: 24 نتیجه
   ✓ Retrieved: 24 documents
🔄 Reranking 24 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 56%|█████▋    | 67/119 [25:29<22:52, 26.39s/it]

📝 Query: در صورتی که مرتکب در مدت تعویق صدور حکم به دستورات دادگاه پایبندی کامل داشته باش...
🔍 روش انتخاب شده: Semantic search
🔍 Semantic only: 24 نتیجه
   ✓ Retrieved: 24 documents
🔄 Reranking 24 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 57%|█████▋    | 68/119 [25:46<19:56, 23.46s/it]

📝 Query: مجازات معاون در اسیدپاشی چه مقدار است؟...
🎯 روش انتخاب شده: Metadata-aware
🎯 Metadata: law='قانون تشدید مجازات اسیدپاشی و حمایت از بزه‌دیدگان ناشی از آن' | None None
🔍 فیلتر فقط قانون...
   ✓ 7 سند (law_only)
🔍 Semantic fallback...
✅ نهایی: 24 نتیجه
   ✓ Retrieved: 24 documents
🔄 Reranking 24 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 58%|█████▊    | 69/119 [26:08<19:12, 23.05s/it]

📝 Query: «الف» مبادرت به حفاری و کاوش به قصد به دست آوردن اموال تاریخی مینماید لیکن هیچ م...
🔍 روش انتخاب شده: Semantic search
🔍 Semantic only: 24 نتیجه
   ✓ Retrieved: 24 documents
🔄 Reranking 24 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 59%|█████▉    | 70/119 [26:39<20:46, 25.45s/it]

📝 Query: فردی   نسبت به پلاک  ثبت ی متعلق به منابع طبیع ی  درخواست آگه ی  ثبت ی  میکند کا...
🎯 روش انتخاب شده: Metadata-aware
🎯 Metadata: law='قانون تعیین تکلیف وضعیت ثبتی اراضی و ساختمان‌های فاقد سند رسمی' | None None
🔍 فیلتر فقط قانون...
   ✓ 0 سند (law_only)
🔍 Semantic fallback...
✅ نهایی: 20 نتیجه
   ✓ Retrieved: 20 documents
🔄 Reranking 20 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 60%|█████▉    | 71/119 [27:04<20:09, 25.20s/it]

📝 Query: – «الف» قصد کشتن «ب» را که محقون الدم است دارد. تیر «الف» کمانه کرده و به «ج» اص...
🔍 روش انتخاب شده: Semantic search
🔍 Semantic only: 24 نتیجه
   ✓ Retrieved: 24 documents
🔄 Reranking 24 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 61%|██████    | 72/119 [27:45<23:25, 29.89s/it]

📝 Query: – «الف» بدافزاری تولید کرده که کارایی ظاهری آن ضبط صدا است ولیکن پس از نصب تمام ...
🎯 روش انتخاب شده: Metadata-aware
🎯 Metadata: law='قانون جرایم رایانه‌ای' | None None
🔍 فیلتر فقط قانون...
   ✓ 10 سند (law_only)
🔍 Semantic fallback...
✅ نهایی: 24 نتیجه
   ✓ Retrieved: 24 documents
🔄 Reranking 24 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 61%|██████▏   | 73/119 [27:54<18:16, 23.83s/it]

📝 Query: «الف» مبادرت به انعقاد قراردادی برای انجام کاری با «ب» مینماید و مبلغ یک میلیارد...
🔍 روش انتخاب شده: Semantic search
🔍 Semantic only: 24 نتیجه
   ✓ Retrieved: 24 documents
🔄 Reranking 24 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 62%|██████▏   | 74/119 [28:38<22:17, 29.73s/it]

📝 Query: قاضی دادگاه در جلسه رسیدگی از کارشناس رسمی دادگستری برای رفع ابهام میزان خسارت و...
🎯 روش انتخاب شده: Metadata-aware
🎯 Metadata: law='قانون کانون کارشناسان رسمی دادگستری' | None None
🔍 فیلتر فقط قانون...
   ✓ 0 سند (law_only)
🔍 Semantic fallback...
✅ نهایی: 20 نتیجه
   ✓ Retrieved: 20 documents
🔄 Reranking 20 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 63%|██████▎   | 75/119 [28:52<18:26, 25.16s/it]

📝 Query: بر کدام یک از اشخاص زیر مجازات کلاهبرداری اعمال نمی شود؟...
🎯 روش انتخاب شده: Metadata-aware
🎯 Metadata: law='قانون مجازات اعمال نفوذ برخلاف حق و مقررات قانونی' | None None
🔍 فیلتر فقط قانون...
   ✓ 0 سند (law_only)
🔍 Semantic fallback...
✅ نهایی: 20 نتیجه
   ✓ Retrieved: 20 documents
🔄 Reranking 20 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 64%|██████▍   | 76/119 [29:19<18:24, 25.68s/it]

📝 Query: آقای «الف» نماینده قانونی شرکت »ب« به جهت تسهیل در اخذ وام دولتی مرتکب رشا با مج...
🎯 روش انتخاب شده: Metadata-aware
🎯 Metadata: law='قانون کاهش مجازات حبس تعزیری' | None None
🔍 فیلتر فقط قانون...
   ✓ 10 سند (law_only)
🔍 Semantic fallback...
✅ نهایی: 24 نتیجه
   ✓ Retrieved: 24 documents
🔄 Reranking 24 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 65%|██████▍   | 77/119 [29:33<15:26, 22.06s/it]

📝 Query: پسر شانزده ساله ای مرتکب جرم ضرب و جرح عمدی با مجازات تعزیری درجه  6 شده است. دا...
🎯 روش انتخاب شده: Metadata-aware
🎯 Metadata: law='قانون کاهش مجازات حبس تعزیری' | None None
🔍 فیلتر فقط قانون...
   ✓ 10 سند (law_only)
🔍 Semantic fallback...
✅ نهایی: 24 نتیجه
   ✓ Retrieved: 24 documents
🔄 Reranking 24 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 66%|██████▌   | 78/119 [30:10<18:10, 26.60s/it]

📝 Query: مردی با جعل سند ملک همسر خود را به عنوان مال خود معرفی و این سند مجعول را به پسر...
🔍 روش انتخاب شده: Semantic search
🔍 Semantic only: 24 نتیجه
   ✓ Retrieved: 24 documents
🔄 Reranking 24 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 66%|██████▋   | 79/119 [30:31<16:41, 25.04s/it]

📝 Query: رسیدگی به جرم قتل غیر عمدی ناشی از تصادفات رانندگی و صدور حکم در خصوص این جرم در...
🎯 روش انتخاب شده: Metadata-aware
🎯 Metadata: law='قانون رسیدگی به تخلفات رانندگی' | None None
🔍 فیلتر فقط قانون...
   ✓ 0 سند (law_only)
🔍 Semantic fallback...
✅ نهایی: 20 نتیجه
   ✓ Retrieved: 20 documents
🔄 Reranking 20 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 67%|██████▋   | 80/119 [30:45<13:58, 21.50s/it]

📝 Query: کدام مورد در خصوص آرای اصداری راجع به جنبه عمومی جرایم غیر عمدی ناشی از کار، صحی...
🔍 روش انتخاب شده: Semantic search
🔍 Semantic only: 24 نتیجه
   ✓ Retrieved: 24 documents
🔄 Reranking 24 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 68%|██████▊   | 81/119 [30:57<11:55, 18.83s/it]

📝 Query: در کدام یک از جرایم زیر امکان جلب مطلق و بدون شرط متهم پرونده بدون ارسال احضاریه...
🔍 روش انتخاب شده: Semantic search
🔍 Semantic only: 24 نتیجه
   ✓ Retrieved: 24 documents
🔄 Reranking 24 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 69%|██████▉   | 82/119 [31:11<10:46, 17.47s/it]

📝 Query: مرجع حل اختلاف در صلاحیت بین دادگاه کیفری دو و دادگاه حقوقی واقع در حوزه قضایی ی...
🔍 روش انتخاب شده: Semantic search
🔍 Semantic only: 24 نتیجه
   ✓ Retrieved: 24 documents
🔄 Reranking 24 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 70%|██████▉   | 83/119 [31:32<10:59, 18.32s/it]

📝 Query: چنانچه ضابط دادگستری فاقد کارت ویژه ضابطان در ارتباط با جرایم مشهود یا در راستای...
🔍 روش انتخاب شده: Semantic search
🔍 Semantic only: 24 نتیجه
   ✓ Retrieved: 24 documents
🔄 Reranking 24 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 71%|███████   | 84/119 [31:47<10:04, 17.28s/it]

📝 Query: در جرایم غیر قابل گذشت چنانچه پس از صدور کیفرخواست و قبل از ارسال به دادگاه، شاک...
🔍 روش انتخاب شده: Semantic search
🔍 Semantic only: 24 نتیجه
   ✓ Retrieved: 24 documents
🔄 Reranking 24 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 71%|███████▏  | 85/119 [32:00<09:09, 16.17s/it]

📝 Query: کدام مورد در خصوص تبعیت دادگاه رسیدگی کننده به امور حقوقی یا ضرر و زیان ناشی از ...
🔍 روش انتخاب شده: Semantic search
🔍 Semantic only: 24 نتیجه
   ✓ Retrieved: 24 documents
🔄 Reranking 24 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 72%|███████▏  | 86/119 [32:13<08:22, 15.23s/it]

📝 Query: در کدام یک از جرایم مشهود زیر در صورت عدم حضور ضابطان دادگستری شهروندان نمی توان...
🔍 روش انتخاب شده: Semantic search
🔍 Semantic only: 24 نتیجه
   ✓ Retrieved: 24 documents
🔄 Reranking 24 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 73%|███████▎  | 87/119 [32:28<07:58, 14.96s/it]

📝 Query: کدام یک از قرارهای دادیار باید در همان روز صدور به نظر دادستان برسد؟...
🔍 روش انتخاب شده: Semantic search
🔍 Semantic only: 24 نتیجه
   ✓ Retrieved: 24 documents
🔄 Reranking 24 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 74%|███████▍  | 88/119 [32:47<08:22, 16.22s/it]

📝 Query: – ضبط اموال یا اشیا از اختیارات کدام مرجع قضایی است؟...
🔍 روش انتخاب شده: Semantic search
🔍 Semantic only: 24 نتیجه
   ✓ Retrieved: 24 documents
🔄 Reranking 24 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 75%|███████▍  | 89/119 [33:15<09:54, 19.83s/it]

📝 Query: اگر دختر 15 سالهای مرتکب جرم تعزیری درجه سه در صلاحیت ذاتی دادگاه انقلاب شود جهت...
🔍 روش انتخاب شده: Semantic search
🔍 Semantic only: 24 نتیجه
   ✓ Retrieved: 24 documents
🔄 Reranking 24 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 76%|███████▌  | 90/119 [33:27<08:24, 17.40s/it]

📝 Query: کدام مورد در خصوص قرار عدم صلاحیت اصداری از دادگاه کیفری یک صحیح است؟...
🔍 روش انتخاب شده: Semantic search
🔍 Semantic only: 24 نتیجه
   ✓ Retrieved: 24 documents
🔄 Reranking 24 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 76%|███████▋  | 91/119 [33:41<07:41, 16.49s/it]

📝 Query: ابتلای به جنون محکوم علیه در جرایم تعزیری پس از صدور حکم قطعی چه تأثیری بر اجرای...
🔍 روش انتخاب شده: Semantic search
🔍 Semantic only: 24 نتیجه
   ✓ Retrieved: 24 documents
🔄 Reranking 24 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 77%|███████▋  | 92/119 [33:58<07:26, 16.53s/it]

📝 Query: تعیین وکیل تسخیری برای اطفال و نوجوانان در کدام یک از جرایم الزامی نیست؟...
🎯 روش انتخاب شده: Metadata-aware
🎯 Metadata: law='قانون حمایت از اطفال و نوجوانان' | None None
🔍 فیلتر فقط قانون...
   ✓ 0 سند (law_only)
🔍 Semantic fallback...
✅ نهایی: 20 نتیجه
   ✓ Retrieved: 20 documents
🔄 Reranking 20 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 78%|███████▊  | 93/119 [34:12<06:48, 15.73s/it]

📝 Query: کدام مورد در خصوص صدور قرار کفالت و وثیقه در جرایم غیر عمدی، صحیح است؟...
🔍 روش انتخاب شده: Semantic search
🔍 Semantic only: 24 نتیجه
   ✓ Retrieved: 24 documents
🔄 Reranking 24 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 79%|███████▉  | 94/119 [34:21<05:43, 13.76s/it]

📝 Query: در کدام یک از جرایم تعزیری زیر در صورت ارائه تضمین لازم برای جبران خسارات وارده ...
🎯 روش انتخاب شده: Metadata-aware
🎯 Metadata: law='قانون بیمه اجباری خسارات وارد شده به شخص ثالث در اثر حوادث ناشی از وسایل نقلیه' | None None
🔍 فیلتر فقط قانون...
   ✓ 0 سند (law_only)
🔍 Semantic fallback...
✅ نهایی: 20 نتیجه
   ✓ Retrieved: 20 documents
🔄 Reranking 20 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 80%|███████▉  | 95/119 [34:31<05:05, 12.74s/it]

📝 Query: کدام مورد در خصوص سوگند به عنوان یکی از ادله اثبات در امور کیفری، صحیح نیست؟...
🔍 روش انتخاب شده: Semantic search
🔍 Semantic only: 24 نتیجه
   ✓ Retrieved: 24 documents
🔄 Reranking 24 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 81%|████████  | 96/119 [34:41<04:30, 11.74s/it]

📝 Query: اگر فردی در کرج متهم به ارتکاب جرم تعزیری درجه دو شود و پس از رسیدگی و صدور حکم ...
🔍 روش انتخاب شده: Semantic search
🔍 Semantic only: 24 نتیجه
   ✓ Retrieved: 24 documents
🔄 Reranking 24 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 82%|████████▏ | 97/119 [34:57<04:48, 13.11s/it]

📝 Query: در مورد احکام قطعی راجع به حقوق عامه و دعاوی مربوط به دولت امور خیریه و اوقاف عا...
🎯 روش انتخاب شده: Metadata-aware
🎯 Metadata: law='قانون آیین دادرسی کیفری' | ماده 477
🔍 فیلتر قانون + شماره (با Range)...
   ✓ 1 سند (law+article_number)
🔍 فیلتر فقط قانون...
   ✓ 10 سند (law_only)
🔍 Semantic fallback...
✅ نهایی: 24 نتیجه
   ✓ Retrieved: 24 documents
🎯 1 نتیجه law+article یافت شد
🔄 Reranking 23 سند دیگر...
   ✓ Reranked: top 6 documents

 82%|████████▏ | 98/119 [35:09<04:28, 12.79s/it]

📝 Query: کدام مورد با آرای وحدت رویه هیئت عمومی دیوان عالی کشور و مقررات قانونی مطابقت ند...
🔍 روش انتخاب شده: Semantic search
🔍 Semantic only: 24 نتیجه
   ✓ Retrieved: 24 documents
🔄 Reranking 24 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 83%|████████▎ | 99/119 [35:25<04:37, 13.88s/it]

📝 Query: به موجب قانون اساس ی ابتکار بودجه کل کشور با کدام مرجع است؟...
🔍 روش انتخاب شده: Semantic search
🔍 Semantic only: 24 نتیجه
   ✓ Retrieved: 24 documents
🔄 Reranking 24 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 84%|████████▍ | 100/119 [35:34<03:56, 12.44s/it]

📝 Query: در قانون اساسی از کدام مورد به عنوان یکی از مصادیق انفال و ثروتهای عمومی یاد شده...
🎯 روش انتخاب شده: Metadata-aware
🎯 Metadata: law='قانون اساسی' | None None
🔍 فیلتر فقط قانون...
   ✓ 10 سند (law_only)
🔍 Semantic fallback...
✅ نهایی: 24 نتیجه
   ✓ Retrieved: 24 documents
🔄 Reranking 24 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 85%|████████▍ | 101/119 [35:45<03:34, 11.92s/it]

📝 Query: طبق قانون اساسی اعمال کدام صلاحیت رئیس قوه قضائیه پس از مشورت امکان پذیر است؟...
🎯 روش انتخاب شده: Metadata-aware
🎯 Metadata: law='قانون اساسی' | None None
🔍 فیلتر فقط قانون...
   ✓ 10 سند (law_only)
🔍 Semantic fallback...
✅ نهایی: 24 نتیجه
   ✓ Retrieved: 24 documents
🔄 Reranking 24 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 86%|████████▌ | 102/119 [36:01<03:42, 13.07s/it]

📝 Query: به موجب قانون اساسی رسیدگی به کدام دعاوی زیر باید به صورت خارج از نوبت انجام گیر...
🎯 روش انتخاب شده: Metadata-aware
🎯 Metadata: law='قانون اساسی' | None None
🔍 فیلتر فقط قانون...
   ✓ 10 سند (law_only)
🔍 Semantic fallback...
✅ نهایی: 24 نتیجه
   ✓ Retrieved: 24 documents
🔄 Reranking 24 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 87%|████████▋ | 103/119 [36:16<03:38, 13.68s/it]

📝 Query: در قانون اساسی به کدام یک از اصول حاکم بر رسیدگیهای قضایی تصریح شده است؟...
🎯 روش انتخاب شده: Metadata-aware
🎯 Metadata: law='قانون اساسی' | None None
🔍 فیلتر فقط قانون...
   ✓ 10 سند (law_only)
🔍 Semantic fallback...
✅ نهایی: 24 نتیجه
   ✓ Retrieved: 24 documents
🔄 Reranking 24 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 87%|████████▋ | 104/119 [36:25<03:05, 12.38s/it]

📝 Query: «منع تبذیر» ذیل ضوابط حاکم بر کدام یک از شئون نظام جمهوری اسلامی در قانون اساسی ...
🎯 روش انتخاب شده: Metadata-aware
🎯 Metadata: law='قانون اساسی' | None None
🔍 فیلتر فقط قانون...
   ✓ 10 سند (law_only)
🔍 Semantic fallback...
✅ نهایی: 24 نتیجه
   ✓ Retrieved: 24 documents
🔄 Reranking 24 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 88%|████████▊ | 105/119 [36:38<02:55, 12.54s/it]

📝 Query: کدام مورد در خصوص تفویض اختیار قانونگذاری از سوی مجلس شورای اسلامی، صحیح است؟...
🔍 روش انتخاب شده: Semantic search
🔍 Semantic only: 24 نتیجه
   ✓ Retrieved: 24 documents
🔄 Reranking 24 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 89%|████████▉ | 106/119 [36:54<02:55, 13.48s/it]

📝 Query: در قانون اساسی کدام آزادی مشروط به رعایت حقوق دیگران شده است؟...
🎯 روش انتخاب شده: Metadata-aware
🎯 Metadata: law='قانون اساسی' | None None
🔍 فیلتر فقط قانون...
   ✓ 10 سند (law_only)
🔍 Semantic fallback...
✅ نهایی: 24 نتیجه
   ✓ Retrieved: 24 documents
🔄 Reranking 24 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 90%|████████▉ | 107/119 [37:03<02:24, 12.04s/it]

📝 Query: بنا به تصریح قانون اساس ی مصوبات کدام مرجع نباید با متن و روح قانون مغایرت داشته...
🔍 روش انتخاب شده: Semantic search
🔍 Semantic only: 24 نتیجه
   ✓ Retrieved: 24 documents
🔄 Reranking 24 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 91%|█████████ | 108/119 [37:12<02:04, 11.35s/it]

📝 Query: در قانون اساسی بر ممنوعیت تبعیض در کدام مورد زیر تصریح شده است؟...
🎯 روش انتخاب شده: Metadata-aware
🎯 Metadata: law='قانون اساسی' | None None
🔍 فیلتر فقط قانون...
   ✓ 10 سند (law_only)
🔍 Semantic fallback...
✅ نهایی: 24 نتیجه
   ✓ Retrieved: 24 documents
🔄 Reranking 24 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 92%|█████████▏| 109/119 [37:21<01:47, 10.71s/it]

📝 Query: بنا به تصریح قانون اساسی سلب کدام یک از حقوق زیر به درخواست خود شخص ذی حق امکان ...
🎯 روش انتخاب شده: Metadata-aware
🎯 Metadata: law='قانون اساسی' | None None
🔍 فیلتر فقط قانون...
   ✓ 10 سند (law_only)
🔍 Semantic fallback...
✅ نهایی: 24 نتیجه
   ✓ Retrieved: 24 documents
🔄 Reranking 24 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 92%|█████████▏| 110/119 [37:30<01:30, 10.10s/it]

📝 Query: کدام مورد از ابعاد حق دادخواهی در قانون اساسی به شمار نمی آید؟...
🎯 روش انتخاب شده: Metadata-aware
🎯 Metadata: law='قانون اساسی' | None None
🔍 فیلتر فقط قانون...
   ✓ 10 سند (law_only)
🔍 Semantic fallback...
✅ نهایی: 24 نتیجه
   ✓ Retrieved: 24 documents
🔄 Reranking 24 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 93%|█████████▎| 111/119 [37:40<01:19,  9.88s/it]

📝 Query: شهروندی که از مصوبه دولت متضرر شده و آن را خلاف قانون میداند همزمان نسبت به مصوب...
🎯 روش انتخاب شده: Metadata-aware
🎯 Metadata: law='قانون اساسی' | اصل 90
🔍 فیلتر قانون + شماره (با Range)...
   ✓ 1 سند (law+principle_number)
🔍 فیلتر فقط قانون...
   ✓ 10 سند (law_only)
🔍 Semantic fallback...
✅ نهایی: 24 نتیجه
   ✓ Retrieved: 24 documents
🎯 1 نتیجه law+article یافت شد
🔄 Reranking 23 سند دیگر...
   ✓ Reranked: top 6 documents

 94%|█████████▍| 112/119 [37:49<01:09,  9.87s/it]

📝 Query: کدام مورد در خصوص اعمال قوه مقننه صحیح است؟...
🔍 روش انتخاب شده: Semantic search
🔍 Semantic only: 24 نتیجه
   ✓ Retrieved: 24 documents
🔄 Reranking 24 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 95%|█████████▍| 113/119 [37:59<00:59,  9.91s/it]

📝 Query: به موجب قانون اساسی کدام مورد ضرورتاً نیاز به تصویب مجلس شورای اسلامی ندارد؟...
🎯 روش انتخاب شده: Metadata-aware
🎯 Metadata: law='قانون اساسی' | None None
🔍 فیلتر فقط قانون...
   ✓ 10 سند (law_only)
🔍 Semantic fallback...
✅ نهایی: 24 نتیجه
   ✓ Retrieved: 24 documents
🔄 Reranking 24 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 96%|█████████▌| 114/119 [38:16<00:59, 11.90s/it]

📝 Query: کارمند شرکت دولتی در ایامی که در مرخصی بدون حقوق به سر میبرد به عنوان مدیر عامل ...
🔍 روش انتخاب شده: Semantic search
🔍 Semantic only: 24 نتیجه
   ✓ Retrieved: 24 documents
🔄 Reranking 24 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 97%|█████████▋| 115/119 [38:26<00:44, 11.24s/it]

📝 Query: شرکتی با اختراع یک دستگاه و فروش عمده آن به کارخانجات خودروسازی موجب بیکار شدن ت...
🔍 روش انتخاب شده: Semantic search
🔍 Semantic only: 24 نتیجه
   ✓ Retrieved: 24 documents
🔄 Reranking 24 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 97%|█████████▋| 116/119 [38:47<00:42, 14.20s/it]

📝 Query: چنانچه مجلس شورای اسلامی طی مصوبه ای تعیین تکلیف استخدام کارشناسان خارجی در وزار...
🎯 روش انتخاب شده: Metadata-aware
🎯 Metadata: law='قانون تعیین تکلیف وضعیت ثبتی اراضی و ساختمان‌های فاقد سند رسمی' | None None
🔍 فیلتر فقط قانون...
   ✓ 0 سند (law_only)
🔍 Semantic fallback...
✅ نهایی: 20 نتیجه
   ✓ Retrieved: 20 documents
🔄 Reranking 20 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 98%|█████████▊| 117/119 [38:58<00:26, 13.46s/it]

📝 Query: شورای اسلامی شهری اقدام به وضع مصوبه ای کرده و به موجب آن هرگونه استخدام در شورا...
🎯 روش انتخاب شده: Metadata-aware
🎯 Metadata: law='قانون مجازات اسلامی مصوب 1375' | None None
🔍 فیلتر فقط قانون...
   ✓ 10 سند (law_only)
🔍 Semantic fallback...
✅ نهایی: 24 نتیجه
   ✓ Retrieved: 24 documents
🔄 Reranking 24 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 99%|█████████▉| 118/119 [39:09<00:12, 12.65s/it]

📝 Query: در قانون اساسی به تعیین تکلیف کدام یک از امور مربوط به هیئت منصفه در جرایم سیاسی...
🎯 روش انتخاب شده: Metadata-aware
🎯 Metadata: law='قانون اساسی' | None None
🔍 فیلتر فقط قانون...
   ✓ 10 سند (law_only)
🔍 Semantic fallback...
✅ نهایی: 24 نتیجه
   ✓ Retrieved: 24 documents
🔄 Reranking 24 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

100%|██████████| 119/119 [39:19<00:00, 19.82s/it]

In [8]:
df_res = pd.DataFrame(results_rows)
display(df_res.head(10))

overall_acc = df_res["is_correct"].mean()
print("Overall accuracy:", overall_acc)

print("\nAccuracy by category:")
print(df_res.groupby("category")["is_correct"].mean())

,question_number,category,gold,pred,is_correct,confidence,needs_revision,critic_issue,critic_action,context_preview,docs_meta
0,1,حقوق مدنی,3,3,True,5,False,no issue,accept answer,[منبع 1] (قانون) - قانون مدنی\nشماره_ماده: 73\...,"[{'i': 1, 'law': None, 'article_number': 73, '..."
1,2,حقوق مدنی,2,2,True,5,True,incorrect option selected,select option 2 instead,[منبع 1] (دادنامه)\ntitle: مبلغ مازاد بر دیه د...,"[{'i': 1, 'law': None, 'article_number': None,..."
2,3,حقوق مدنی,"2,4",4,True,5,False,no issue,accept answer,[منبع 1] (قانون) - قانون مدنی\nشماره_ماده: 139...,"[{'i': 1, 'law': None, 'article_number': 139, ..."
3,4,حقوق مدنی,"1,4",4,True,5,False,no issue,accept answer,[منبع 1] (دادنامه) - قانون آیین دادرسی مدنی | ...,"[{'i': 1, 'law': None, 'article_number': None,..."
4,5,حقوق مدنی,3,3,True,5,False,no issue,accept answer,[منبع 1] (وحدت رویه) - قانون مدنی\ntitle: عدم ...,"[{'i': 1, 'law': None, 'article_number': None,..."
5,6,حقوق مدنی,3,4,False,5,True,incorrect answer choice,select correct option based on sources,[منبع 1] (قانون) - قانون مدنی\nشماره_ماده: 795...,"[{'i': 1, 'law': None, 'article_number': 795, ..."
6,7,حقوق مدنی,1,4,False,5,True,contradicts source 4,must align with trade law,[منبع 1] (قانون) - قانون امور حسبی\nشماره_ماده...,"[{'i': 1, 'law': None, 'article_number': 94, '..."
7,8,حقوق مدنی,4,1,False,5,True,conflict with sources on right to rescind,revise explanation to align with Source 3,[منبع 1] (دادنامه) - قانون مدنی\ntitle: رد درخ...,"[{'i': 1, 'law': None, 'article_number': None,..."
8,9,حقوق مدنی,"1,2",4,False,5,False,no issue,accept answer,[منبع 1] (دادنامه)\ntitle: مسئولیت دولت ناشی ا...,"[{'i': 1, 'law': None, 'article_number': None,..."
9,10,حقوق مدنی,3,3,True,5,False,no issue,accept answer,[منبع 1] (قانون) - قانون مدنی\nشماره_ماده: 118...,"[{'i': 1, 'law': None, 'article_number': 1188,..."

Overall accuracy: 0.5546218487394958

Accuracy by category:
category
آیین دادرسی مدنی     0.450000
آیین دادرسی کیفری    0.750000
حقوق اساسی           0.750000
حقوق تجارت           0.550000
حقوق جزا             0.315789
حقوق مدنی            0.500000
Name: is_correct, dtype: float64

In [18]:
import pandas as pd
wrong_answers = df_res[df_res["is_correct"] == False]

wrong_answers.to_csv('wrong_answers.csv')