In [10]:
# %%
# Notebook 08: 08_eval_full_dataset.ipynb
# هدف: اجرای کامل گراف روی structured_questions.csv و محاسبه Accuracy کلی و per-category

import os, sys, time, json, traceback
from pathlib import Path

import pandas as pd
from tqdm import tqdm

PROJECT_ROOT = Path.cwd().parent  # اگر داخل notebooks هستی
SRC_PATH = PROJECT_ROOT / "src"
sys.path.insert(0, str(SRC_PATH))

from dotenv import load_dotenv
load_dotenv()

print(f"✓ PROJECT_ROOT: {PROJECT_ROOT}")
print(f"✓ SRC_PATH: {SRC_PATH}")
print("✓ OPENROUTER_API_KEY:", (os.getenv("OPENROUTER_API_KEY") or "")[:10], "...")
print("✓ COHERE_API_KEY:", (os.getenv("COHERE_API_KEY") or "")[:10], "...")

✓ PROJECT_ROOT: f:\Thesis\project\3-Multi-Agent-System
✓ SRC_PATH: f:\Thesis\project\3-Multi-Agent-System\src
✓ OPENROUTER_API_KEY: sk-or-v1-1 ...
✓ COHERE_API_KEY: O0pIM8Zkm9 ...

In [11]:
# %%
from legal_multi_agent.graphs.main_graph import graph

print("✓ Graph imported")

✓ Graph imported

In [12]:
# %%
QUESTIONS_PATH = r"F:\Thesis\project\403-vekalat\structured_questions.csv"
GOLD_PATH      = r"F:\Thesis\project\1-BaselineTest\GOLD\Gold.csv"

df_q = pd.read_csv(QUESTIONS_PATH)
df_gold = pd.read_csv(GOLD_PATH)

print("Questions:", len(df_q))
print("Gold:", len(df_gold))

display(df_q.head(2))
display(df_gold.head(2))

Questions: 119
Gold: 119

,question_number,category,question,options
0,1,حقوق مدنی,کدام یک از موارد زیر صحیح است؟,1) با توافق طرفین امکان از بین بردن سبب انفساخ...
1,2,حقوق مدنی,شخص «الف» حین رانندگی با خودرو سواری با شخص «ب...,1) دیه هر دو راننده صرفاً تا میزان دیه کامل و ...

   idx Gold
0    1    3
1    2    2

In [13]:
# %%
# حذف سوال 89
if "idx" in df_gold.columns and 89 in df_gold["idx"].values:
    df_gold = df_gold[df_gold["idx"] != 89].reset_index(drop=True)

multi_gold = {
    90: ["3", "4"],
    53: ["1", "2"],
    52: ["2", "4"],
    48: ["1", "3"],
    46: ["1", "3"],
    36: ["1", "4"],
    30: ["1", "2"],
    25: ["3", "4"],
    9:  ["1", "2"],
    4:  ["1", "4"],
    3:  ["2", "4"],
}

def normalize_gold_value(idx: int, gold_val: str) -> str:
    if idx in multi_gold:
        return ",".join(multi_gold[idx])

    val = str(gold_val).strip()
    digits = [ch for ch in val if ch.isdigit()]
    if not digits:
        return val
    if len(digits) == 1:
        return digits[0]
    return ",".join(digits)

df_gold["Gold"] = [
    normalize_gold_value(int(idx), gold)
    for idx, gold in zip(df_gold["idx"], df_gold["Gold"])
]

display(df_gold.head(5))

   idx Gold
0    1    3
1    2    2
2    3  2,4
3    4  1,4
4    5    3

In [14]:
# %%
def parse_options_to_text(options_raw) -> str:
    """تبدیل ستون options به متن استاندارد برای گراف."""
    if options_raw is None or (isinstance(options_raw, float) and pd.isna(options_raw)):
        return ""
    s = str(options_raw).strip()

    # اگر JSON-لایک بود
    if s.startswith("[") or s.startswith("{"):
        try:
            obj = json.loads(s)
            if isinstance(obj, list):
                lines = []
                for i, item in enumerate(obj, start=1):
                    lines.append(f"{i}) {str(item).strip()}")
                return "\n".join(lines)
        except Exception:
            pass

    return s

def is_correct(pred: str, gold: str) -> bool:
    gold_set = {g.strip() for g in str(gold).split(",") if g.strip()}
    return str(pred).strip() in gold_set

In [15]:
# %%
df = df_q.copy()

# اطمینان از اسم ستون‌ها
assert "question_number" in df.columns
assert "question" in df.columns
assert "options" in df.columns

assert "idx" in df_gold.columns
assert "Gold" in df_gold.columns

df = df.merge(df_gold[["idx", "Gold"]], left_on="question_number", right_on="idx", how="left")
df.drop(columns=["idx"], inplace=True)

print("Merged rows:", len(df))
print("Gold missing:", df["Gold"].isna().mean())
display(df.head(3))

Merged rows: 119
Gold missing: 0.0

,question_number,category,question,options,Gold
0,1,حقوق مدنی,کدام یک از موارد زیر صحیح است؟,1) با توافق طرفین امکان از بین بردن سبب انفساخ...,3
1,2,حقوق مدنی,شخص «الف» حین رانندگی با خودرو سواری با شخص «ب...,1) دیه هر دو راننده صرفاً تا میزان دیه کامل و ...,2
2,3,حقوق مدنی,کدام مورد در خصوص تصرفی که همراه با قصد تملک ب...,1) تصرف در مواردی مملک است حتی اگر همراه با قص...,"2,4"

In [16]:
# %%
USE_OPTION_VERIFIER = True
USE_RETRIEVER_TOOL  = True

MAX_REVISIONS = 2
SLEEP_SECONDS = 0.2  

OUT_PATH = PROJECT_ROOT / "data" / "eval" / "notebook08_full_v2_results.csv"
OUT_PATH.parent.mkdir(parents=True, exist_ok=True)

print("Output will be saved to:", OUT_PATH)

Output will be saved to: f:\Thesis\project\3-Multi-Agent-System\data\eval\notebook08_full_v2_results.csv

In [17]:
from tqdm import tqdm 

def run_one(row) -> dict:
    qnum = int(row["question_number"])

    question = str(row["question"])
    options_text = parse_options_to_text(row["options"])

    state = {
        "question_number": qnum,
        "question": question,
        "options_text": options_text,
        "max_revisions": MAX_REVISIONS,
        "use_option_verifier": USE_OPTION_VERIFIER,
        "use_retriever_tool": USE_RETRIEVER_TOOL,
        "messages": [],
        "tool_results": {},
        "verifier_output": None,
        "revision_count": 0,
    }

    t0 = time.time()
    try:
        result = graph.invoke(state)
        elapsed = time.time() - t0

        final = result.get("final_toon") or {}
        pred = final.get("answer")
        conf = final.get("confidence")
        expl = final.get("explanation")

        tqdm.write(f"[Q{qnum}] pred={pred} | conf={conf}")


        # ✅ این بخش اضافه شده: چاپ پاسخ انتخابی مدل
        gold = row.get("Gold")
        ok = (is_correct(pred, gold) if pd.notna(gold) and pred else None)

        critic = result.get("critic_toon") or {}
        critic_needs = critic.get("needs_revision")

        verifier = result.get("verifier_output") or {}
        v_rec = verifier.get("recommended_answer")
        v_conf = verifier.get("confidence")

        ctx = result.get("context") or ""
        rag_results = result.get("rag_results") or []

        return {
            "question_number": qnum,
            "pred": pred,
            "confidence": conf,
            "explanation": expl,
            "gold": gold,
            "is_correct": ok,
            "critic_needs_revision": critic_needs,
            "revision_count": result.get("revision_count"),
            "verifier_recommended": v_rec,
            "verifier_confidence": v_conf,
            "context_len": len(ctx),
            "n_docs": len(rag_results),
            "elapsed_sec": elapsed,
            "error": None,
        }

    except Exception as e:
        elapsed = time.time() - t0

        # ✅ چاپ خطا برای همان سؤال
        tqdm.write(f"[Q{qnum}] ERROR: {type(e).__name__}: {str(e)[:200]}")

        return {
            "question_number": qnum,
            "pred": None,
            "confidence": None,
            "explanation": None,
            "gold": row.get("Gold"),
            "is_correct": None,
            "critic_needs_revision": None,
            "revision_count": None,
            "verifier_recommended": None,
            "verifier_confidence": None,
            "context_len": None,
            "n_docs": None,
            "elapsed_sec": elapsed,
            "error": f"{type(e).__name__}: {str(e)}",
        }

In [18]:
# %%
done_set = set()
if OUT_PATH.exists():
    df_done = pd.read_csv(OUT_PATH)
    done_set = set(df_done["question_number"].astype(int).tolist())
    print("Resuming. Already done:", len(done_set))

rows_out = []
if OUT_PATH.exists():
    rows_out = df_done.to_dict("records")

for _, row in tqdm(df.iterrows(), total=len(df)):
    qnum = int(row["question_number"])
    if qnum in done_set:
        continue

    r = run_one(row)
    rows_out.append(r)
    done_set.add(qnum)

    # ذخیره دوره‌ای
    if len(rows_out) % 10 == 0:
        pd.DataFrame(rows_out).to_csv(OUT_PATH, index=False, encoding="utf-8-sig")

    time.sleep(SLEEP_SECONDS)

df_res_v2 = pd.DataFrame(rows_out)
df_res_v2.to_csv(OUT_PATH, index=False, encoding="utf-8-sig")
print("Saved to:", OUT_PATH)
print("Rows in result:", len(df_res_v2))

  0%|          | 0/119 [00:00<?, ?it/s]

📝 Query: کدام یک از موارد زیر صحیح است؟

گزینه‌ها:
1) با توافق طرفین امکان از بین بردن سب...
🔍 روش انتخاب شده: Semantic search
🔍 Semantic only: 24 نتیجه
   ✓ Retrieved: 24 documents
🔄 Reranking 24 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

  0%|          | 0/119 [00:22<?, ?it/s]

   ⚠️ [Critic] needs_revision=true but no valid citation → forcing false
[Q1] pred=3 | conf=5

  1%|          | 1/119 [00:22<43:53, 22.32s/it]

📝 Query: شخص «الف» حین رانندگی با خودرو سواری با شخص «ب» (موتورسوار) تصادف می کند شخص «ال...
🎯 روش انتخاب شده: Metadata-aware
🎯 Metadata: law='قانون بیمه اجباری خسارات وارد شده به شخص ثالث در اثر حوادث ناشی از وسایل نقلیه' | None None
🔍 فیلتر فقط قانون...
   ✓ 0 سند (law_only)
🔍 Semantic fallback...
✅ نهایی: 20 نتیجه
   ✓ Retrieved: 20 documents
🔄 Reranking 20 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

  1%|          | 1/119 [00:46<43:53, 22.32s/it]

   ⚠️ [Critic] needs_revision=true but no valid citation → forcing false
[Q2] pred=2 | conf=5

  2%|▏         | 2/119 [00:46<45:20, 23.25s/it]

📝 Query: کدام مورد در خصوص تصرفی که همراه با قصد تملک باشد صحیح است؟

گزینه‌ها:
1) تصرف د...
🔍 روش انتخاب شده: Semantic search
🔍 Semantic only: 24 نتیجه
   ✓ Retrieved: 24 documents
🔄 Reranking 24 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

  2%|▏         | 2/119 [01:09<45:20, 23.25s/it]

   ⚠️ [Critic] needs_revision=true but no valid citation → forcing false
[Q3] pred=4 | conf=5

  3%|▎         | 3/119 [01:09<44:56, 23.25s/it]

📝 Query: شخص «الف» (جراح پلاستیک زیبایی) که تحت پوشش کامل بیمه مسئولیت مدنی ناشی از تقصیر...
🎯 روش انتخاب شده: Metadata-aware
🎯 Metadata: law='قانون مسئولیت مدنی' | None None
🔍 فیلتر فقط قانون...
   ✓ 10 سند (law_only)
🔍 Semantic fallback...
✅ نهایی: 24 نتیجه
   ✓ Retrieved: 24 documents
🔄 Reranking 24 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

  3%|▎         | 3/119 [01:41<44:56, 23.25s/it]

   ⚠️ [Critic] needs_revision=true but no valid citation → forcing false
[Q4] pred=3 | conf=5

  3%|▎         | 4/119 [01:41<51:30, 26.87s/it]

📝 Query: شرط وکالت زن در طلاق در چه قالب هایی قابل تحقق است؟

گزینه‌ها:
1) به شکل شرط نتی...
🔍 روش انتخاب شده: Semantic search
🔍 Semantic only: 24 نتیجه
   ✓ Retrieved: 24 documents
🔄 Reranking 24 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

  3%|▎         | 4/119 [02:00<51:30, 26.87s/it]

   ⚠️ [Critic] needs_revision=true but no valid citation → forcing false
[Q5] pred=3 | conf=5

  4%|▍         | 5/119 [02:00<45:26, 23.91s/it]

📝 Query: کدام مورد در خصوص تشابه »هبه« و »وصیت تملیکی«، صحیح است؟

گزینه‌ها:
1) هر دو جزو...
🔍 روش انتخاب شده: Semantic search
🔍 Semantic only: 24 نتیجه
   ✓ Retrieved: 24 documents
🔄 Reranking 24 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

  4%|▍         | 5/119 [02:21<45:26, 23.91s/it]

   ⚠️ [Critic] needs_revision=true but no valid citation → forcing false
[Q6] pred=4 | conf=5

  5%|▌         | 6/119 [02:21<43:11, 22.93s/it]

📝 Query: مسئولیت کدام یک از اشخاص زیر در مقابل متعهدله یا زیان دیده به تسهیم است نه تضامن...
🔍 روش انتخاب شده: Semantic search
🔍 Semantic only: 24 نتیجه
   ✓ Retrieved: 24 documents
🔄 Reranking 24 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

  5%|▌         | 6/119 [02:37<43:11, 22.93s/it]

   ⚠️ [Critic] needs_revision=true but no valid citation → forcing false
[Q7] pred=1 | conf=4

  6%|▌         | 7/119 [02:38<38:51, 20.81s/it]

📝 Query: در قرارداد فروش مالی شرط می شود که چنانچه ثمن معامله ظرف مدت یک ماه پرداخت نشود ...
🔍 روش انتخاب شده: Semantic search
🔍 Semantic only: 24 نتیجه
   ✓ Retrieved: 24 documents
🔄 Reranking 24 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

  6%|▌         | 7/119 [02:51<38:51, 20.81s/it]

   ⚠️ [Critic] needs_revision=true but no valid citation → forcing false
[Q8] pred=1 | conf=5

  7%|▋         | 8/119 [02:51<34:04, 18.42s/it]

📝 Query: چنانچه مسئولیت مدنی مبتنی بر تقصیر باشد کدام یک از اشخاص زیر در برابر زیان دیده ...
🎯 روش انتخاب شده: Metadata-aware
🎯 Metadata: law='قانون کار' | None None
🔍 فیلتر فقط قانون...
   ✓ 0 سند (law_only)
🔍 Semantic fallback...
✅ نهایی: 20 نتیجه
   ✓ Retrieved: 20 documents
🔄 Reranking 20 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

  7%|▋         | 8/119 [03:08<34:04, 18.42s/it]

   ⚠️ [Critic] needs_revision=true but no valid citation → forcing false
[Q9] pred=2 | conf=5

  8%|▊         | 9/119 [03:08<33:15, 18.14s/it]

📝 Query: پدر برای اداره اموال فرزندان صغیرش بعد از فوت خود برادرش را به عنوان وصی تعیین م...
🔍 روش انتخاب شده: Semantic search
🔍 Semantic only: 24 نتیجه
   ✓ Retrieved: 24 documents
🔄 Reranking 24 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

  8%|▊         | 9/119 [03:29<33:15, 18.14s/it]

   ⚠️ [Critic] needs_revision=true but no valid citation → forcing false
[Q10] pred=2 | conf=3

  8%|▊         | 10/119 [03:29<34:30, 19.00s/it]

📝 Query: کدام مورد در خصوص تشابه و تفاوت تعلیق در مرحله انعقاد قرارداد و تعلیق در مرحله ا...
🔍 روش انتخاب شده: Semantic search
🔍 Semantic only: 24 نتیجه
   ✓ Retrieved: 24 documents
🔄 Reranking 24 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

  8%|▊         | 10/119 [03:58<34:30, 19.00s/it]

   ⚠️ [Critic] needs_revision=true but no valid citation → forcing false
[Q11] pred=1 | conf=3

  9%|▉         | 11/119 [03:58<39:25, 21.90s/it]

📝 Query: أجل برای انجام تعهدات قراردادی ناشی از کدام یک از موارد زیر می تواند باشد؟

گزین...
🔍 روش انتخاب شده: Semantic search
🔍 Semantic only: 24 نتیجه
   ✓ Retrieved: 24 documents
🔄 Reranking 24 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

  9%|▉         | 11/119 [04:21<39:25, 21.90s/it]

   ⚠️ [Critic] needs_revision=true but no valid citation → forcing false
[Q12] pred=4 | conf=4

 10%|█         | 12/119 [04:21<39:59, 22.42s/it]

📝 Query: کدام مورد در خصوص تفاوت و تشابه عقد و ایقاع صحیح نیست ؟

گزینه‌ها:
1) عقد می توا...
🔍 روش انتخاب شده: Semantic search
🔍 Semantic only: 24 نتیجه
   ✓ Retrieved: 24 documents
🔄 Reranking 24 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 10%|█         | 12/119 [04:38<39:59, 22.42s/it]

   ⚠️ [Critic] needs_revision=true but no valid citation → forcing false
[Q13] pred=1 | conf=2

 11%|█         | 13/119 [04:38<36:29, 20.66s/it]

📝 Query: با توجه به قانون روابط موجر و مستأجر 1376 کدام مورد صحیح است؟

گزینه‌ها:
1) مستا...
🎯 روش انتخاب شده: Metadata-aware
🎯 Metadata: law='قانون روابط موجر و مستاجر مصوب 1356' | None None
🔍 فیلتر فقط قانون...
   ✓ 0 سند (law_only)
🔍 Semantic fallback...
✅ نهایی: 20 نتیجه
   ✓ Retrieved: 20 documents
🔄 Reranking 20 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 11%|█         | 13/119 [04:52<36:29, 20.66s/it]

   ⚠️ [Critic] needs_revision=true but no valid citation → forcing false
[Q14] pred=4 | conf=5

 12%|█▏        | 14/119 [04:52<32:53, 18.79s/it]

📝 Query: کدام مورد در خصوص حقوق پدیدآورندگان آثار، صحیح نیست؟

گزینه‌ها:
1) حق بهره بردار...
🔍 روش انتخاب شده: Semantic search
🔍 Semantic only: 24 نتیجه
   ✓ Retrieved: 24 documents
🔄 Reranking 24 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 12%|█▏        | 14/119 [05:17<32:53, 18.79s/it]

   ⚠️ [Critic] needs_revision=true but no valid citation → forcing false
[Q15] pred=2 | conf=5

 13%|█▎        | 15/119 [05:17<35:42, 20.60s/it]

📝 Query: « الف» به عنوان وکیل »ب« ملک »ب« را به یک سوم قیمت عرفی به «ج» واگذار می کند. با...
🔍 روش انتخاب شده: Semantic search
🔍 Semantic only: 24 نتیجه
   ✓ Retrieved: 24 documents
🔄 Reranking 24 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 13%|█▎        | 15/119 [05:32<35:42, 20.60s/it]

   ⚠️ [Critic] needs_revision=true but no valid citation → forcing false
[Q16] pred=1 | conf=5

 13%|█▎        | 16/119 [05:32<32:16, 18.80s/it]

📝 Query: کدام مورد در خصوص رد ترکه، صحیح است؟

گزینه‌ها:
1) رد مطلق ترکه ممکن نیست ولی رد...
🔍 روش انتخاب شده: Semantic search
🔍 Semantic only: 24 نتیجه
   ✓ Retrieved: 24 documents
🔄 Reranking 24 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 13%|█▎        | 16/119 [05:55<32:16, 18.80s/it]

   ⚠️ [Critic] needs_revision=true but no valid citation → forcing false
[Q17] pred=3 | conf=5

 14%|█▍        | 17/119 [05:55<34:13, 20.13s/it]

📝 Query: شخصی فوت می کند که حین الفوت همسرش باردار بوده و پدر و مادرش در قید حیات نیستند ...
🔍 روش انتخاب شده: Semantic search
🔍 Semantic only: 24 نتیجه
   ✓ Retrieved: 24 documents
🔄 Reranking 24 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 14%|█▍        | 17/119 [06:21<34:13, 20.13s/it]

   ⚠️ [Critic] needs_revision=true but no valid citation → forcing false
[Q18] pred=2 | conf=4

 15%|█▌        | 18/119 [06:22<37:05, 22.04s/it]

📝 Query: عین معین متعلق به متعهدله نزد متعهد است، متعهد به جای آن مال، مال دیگری به متعهد...
🔍 روش انتخاب شده: Semantic search
🔍 Semantic only: 24 نتیجه
   ✓ Retrieved: 24 documents
🔄 Reranking 24 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 15%|█▌        | 18/119 [06:39<37:05, 22.04s/it]

   ⚠️ [Critic] needs_revision=true but no valid citation → forcing false
[Q19] pred=2 | conf=5

 16%|█▌        | 19/119 [06:39<34:20, 20.61s/it]

📝 Query: آیا مستعیر می تواند از جهت تعهد به حفاظت و اداره مال، مال عاریه را به تصرف غیر د...
🎯 روش انتخاب شده: Metadata-aware
🎯 Metadata: law='قانون آیین دادرسی مدنی' | None None
🔍 فیلتر فقط قانون...
   ✓ 0 سند (law_only)
🔍 Semantic fallback...
✅ نهایی: 20 نتیجه
   ✓ Retrieved: 20 documents
🔄 Reranking 20 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 16%|█▌        | 19/119 [07:00<34:20, 20.61s/it]

   ⚠️ [Critic] needs_revision=true but no valid citation → forcing false
[Q20] pred=2 | conf=5

 17%|█▋        | 20/119 [07:00<34:12, 20.73s/it]

📝 Query: چنانچه آیین نامه دولتی با صدور رأی هیئت عمومی دیوان عدالت اداری ابطال شود، در خص...
🎯 روش انتخاب شده: Metadata-aware
🎯 Metadata: law='قانون دیوان عدالت اداری' | None None
🔍 فیلتر فقط قانون...
   ✓ 10 سند (law_only)
🔍 Semantic fallback...
✅ نهایی: 24 نتیجه
   ✓ Retrieved: 24 documents
🔄 Reranking 24 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 17%|█▋        | 20/119 [07:15<34:12, 20.73s/it]

   ⚠️ [Critic] needs_revision=true but no valid citation → forcing false
[Q21] pred=2 | conf=5

 18%|█▊        | 21/119 [07:16<31:25, 19.24s/it]

📝 Query: دو شخص که اختلاف خود را برای فصل، به سه نفر داور ارجاع دادهاند. پس از ارجاع به د...
🔍 روش انتخاب شده: Semantic search
🔍 Semantic only: 24 نتیجه
   ✓ Retrieved: 24 documents
🔄 Reranking 24 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 18%|█▊        | 21/119 [07:46<31:25, 19.24s/it]

   ⚠️ [Critic] needs_revision=true but no valid citation → forcing false
[Q22] pred=3 | conf=5

 18%|█▊        | 22/119 [07:46<36:25, 22.53s/it]

📝 Query: حکمی در تأیید حکم دادگاه نخستین از دادگاه تجدیدنظر استان صادر و در مهلت مقرر از ...
🔍 روش انتخاب شده: Semantic search
🔍 Semantic only: 24 نتیجه
   ✓ Retrieved: 24 documents
🔄 Reranking 24 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 18%|█▊        | 22/119 [08:10<36:25, 22.53s/it]

   ⚠️ [Critic] needs_revision=true but no valid citation → forcing false
[Q23] pred=4 | conf=5

 19%|█▉        | 23/119 [08:11<37:09, 23.23s/it]

📝 Query: حکمی قطعی از دادگاه تجدید نظر استان، له شخص «الف» با وکالت شخص «ج» علیه شخص «ب» ...
🔍 روش انتخاب شده: Semantic search
🔍 Semantic only: 24 نتیجه
   ✓ Retrieved: 24 documents
🔄 Reranking 24 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 19%|█▉        | 23/119 [08:34<37:09, 23.23s/it]

   ⚠️ [Critic] needs_revision=true but no valid citation → forcing false
[Q24] pred=1 | conf=4

 20%|██        | 24/119 [08:35<37:06, 23.43s/it]

📝 Query: در خصوص رعایت اصول و تشریفات دادرسی در رسیدگی به امور حقوقی با توجه به قانون شور...
🎯 روش انتخاب شده: Metadata-aware
🎯 Metadata: law='قانون شوراهای حل اختلاف' | None None
🔍 فیلتر فقط قانون...
   ✓ 10 سند (law_only)
🔍 Semantic fallback...
✅ نهایی: 24 نتیجه
   ✓ Retrieved: 24 documents
🔄 Reranking 24 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 20%|██        | 24/119 [08:56<37:06, 23.43s/it]

   ⚠️ [Critic] needs_revision=true but no valid citation → forcing false
[Q25] pred=4 | conf=5

 21%|██        | 25/119 [08:56<35:39, 22.76s/it]

📝 Query: با توجه به قانون شوراهای حل اختلاف مصوب 1402 و قانون تشکیل دادگاههای خانواده تحر...
🎯 روش انتخاب شده: Metadata-aware
🎯 Metadata: law='قانون شوراهای حل اختلاف' | None None
🔍 فیلتر فقط قانون...
   ✓ 10 سند (law_only)
🔍 Semantic fallback...
✅ نهایی: 24 نتیجه
   ✓ Retrieved: 24 documents
🔄 Reranking 24 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 21%|██        | 25/119 [09:26<35:39, 22.76s/it]

   ⚠️ [Critic] needs_revision=true but no valid citation → forcing false
[Q26] pred=4 | conf=4

 22%|██▏       | 26/119 [09:26<38:50, 25.06s/it]

📝 Query: داد خواستی در دیوان عدالت اداری مطرح شده که شاکیان آن پنج نفر می باشند. در خصوص ...
🎯 روش انتخاب شده: Metadata-aware
🎯 Metadata: law='قانون دیوان عدالت اداری' | None None
🔍 فیلتر فقط قانون...
   ✓ 10 سند (law_only)
🔍 Semantic fallback...
✅ نهایی: 24 نتیجه
   ✓ Retrieved: 24 documents
🔄 Reranking 24 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 22%|██▏       | 26/119 [09:52<38:50, 25.06s/it]

   ⚠️ [Critic] needs_revision=true but no valid citation → forcing false
[Q27] pred=2 | conf=5

 23%|██▎       | 27/119 [09:53<39:00, 25.44s/it]

📝 Query: سندی در خارج از کشور تنظیم شده و نماینده کنسولی موافقت آن را با قوانین کشور محل ...
🔍 روش انتخاب شده: Semantic search
🔍 Semantic only: 24 نتیجه
   ✓ Retrieved: 24 documents
🔄 Reranking 24 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 23%|██▎       | 27/119 [10:24<39:00, 25.44s/it]

   ⚠️ [Critic] needs_revision=true but no valid citation → forcing false
[Q28] pred=1 | conf=5

 24%|██▎       | 28/119 [10:24<41:30, 27.37s/it]

📝 Query: در خصوص مهلت اعتراض به نظریه کارشناسی در پرونده دادرسی و ارزیاب در اجرای احکام م...
🎯 روش انتخاب شده: Metadata-aware
🎯 Metadata: law='قانون اجرای احکام مدنی' | None None
🔍 فیلتر فقط قانون...
   ✓ 10 سند (law_only)
🔍 Semantic fallback...
✅ نهایی: 24 نتیجه
   ✓ Retrieved: 24 documents
🔄 Reranking 24 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 24%|██▎       | 28/119 [10:43<41:30, 27.37s/it]

   ⚠️ [Critic] needs_revision=true but no valid citation → forcing false
[Q29] pred=3 | conf=4

 24%|██▍       | 29/119 [10:43<37:09, 24.77s/it]

📝 Query: در خصوص قابلیت فرجام احکام صادره از دادگاه تجدید نظر راجع به متفرعات دعوی که ضمن...
🎯 روش انتخاب شده: Metadata-aware
🎯 Metadata: law='None' | اصل نکاح
🔍 Semantic fallback...
✅ نهایی: 20 نتیجه
   ✓ Retrieved: 20 documents
🔄 Reranking 20 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 24%|██▍       | 29/119 [10:57<37:09, 24.77s/it]

   ⚠️ [Critic] needs_revision=true but no valid citation → forcing false
[Q30] pred=3 | conf=5

 25%|██▌       | 30/119 [10:57<32:05, 21.64s/it]

📝 Query: در دعوایی که به خواسته پرداخت ده میلیارد ریال علیه شخص «الف» و شخص «ب» اقامه شده...
🔍 روش انتخاب شده: Semantic search
🔍 Semantic only: 24 نتیجه
   ✓ Retrieved: 24 documents
🔄 Reranking 24 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 25%|██▌       | 30/119 [11:11<32:05, 21.64s/it]

   ⚠️ [Critic] needs_revision=true but no valid citation → forcing false
[Q31] pred=1 | conf=4

 26%|██▌       | 31/119 [11:11<28:23, 19.36s/it]

📝 Query: حکم خلع ید از یک باب ویلا، له شخص «الف» و علیه شخص «ب» صادر، قطعی و اجرا می شود....
🔍 روش انتخاب شده: Semantic search
🔍 Semantic only: 24 نتیجه
   ✓ Retrieved: 24 documents
🔄 Reranking 24 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 26%|██▌       | 31/119 [11:25<28:23, 19.36s/it]

   ⚠️ [Critic] needs_revision=true but no valid citation → forcing false
[Q32] pred=1 | conf=2

 27%|██▋       | 32/119 [11:25<25:34, 17.64s/it]

📝 Query: چنانچه هر یک از اصحاب دعوی اصول استاد عادی را که رو گرفت آنها را ارائه کرده اند ...
🔍 روش انتخاب شده: Semantic search
🔍 Semantic only: 24 نتیجه
   ✓ Retrieved: 24 documents
🔄 Reranking 24 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 27%|██▋       | 32/119 [11:38<25:34, 17.64s/it]

   ⚠️ [Critic] needs_revision=true but no valid citation → forcing false
[Q33] pred=4 | conf=5

 28%|██▊       | 33/119 [11:38<23:21, 16.30s/it]

📝 Query: در خصوص بازداشت یک حلقه انگشتری گران قیمت، کدام مورد صحیح است؟

گزینه‌ها:
1) بای...
🔍 روش انتخاب شده: Semantic search
🔍 Semantic only: 24 نتیجه
   ✓ Retrieved: 24 documents
🔄 Reranking 24 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 28%|██▊       | 33/119 [11:55<23:21, 16.30s/it]

   ⚠️ [Critic] needs_revision=true but no valid citation → forcing false
[Q34] pred=2 | conf=5

 29%|██▊       | 34/119 [11:56<23:29, 16.58s/it]

📝 Query: خوانده دعوی برای اثبات ادعای خود مبنی بر مطالبه وجه نقد، دو گواه معرفی می کند دا...
🔍 روش انتخاب شده: Semantic search
🔍 Semantic only: 24 نتیجه
   ✓ Retrieved: 24 documents
🔄 Reranking 24 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 29%|██▊       | 34/119 [12:07<23:29, 16.58s/it]

   ⚠️ [Critic] needs_revision=true but no valid citation → forcing false
[Q35] pred=4 | conf=5

 29%|██▉       | 35/119 [12:07<21:08, 15.10s/it]

📝 Query: در دعوایی که خواسته آن چهل میلیون ریال تقویم شده است، حکمی از دادگاه صلح صادر و ...
🔍 روش انتخاب شده: Semantic search
🔍 Semantic only: 24 نتیجه
   ✓ Retrieved: 24 documents
🔄 Reranking 24 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 29%|██▉       | 35/119 [12:24<21:08, 15.10s/it]

   ⚠️ [Critic] needs_revision=true but no valid citation → forcing false
[Q36] pred=3 | conf=5

 30%|███       | 36/119 [12:24<21:48, 15.77s/it]

📝 Query: حکمی از دادگاه تجدیدنظر استان صادر و قطعی شده و عملیات اجرایی حکم در حال انجام ا...
🎯 روش انتخاب شده: Metadata-aware
🎯 Metadata: law='قانون نحوه اجرای محکومیت‌های مالی' | None None
🔍 فیلتر فقط قانون...
   ✓ 10 سند (law_only)
🔍 Semantic fallback...
✅ نهایی: 24 نتیجه
   ✓ Retrieved: 24 documents
🔄 Reranking 24 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 30%|███       | 36/119 [12:38<21:48, 15.77s/it]

   ⚠️ [Critic] needs_revision=true but no valid citation → forcing false
[Q37] pred=1 | conf=2

 31%|███       | 37/119 [12:38<20:44, 15.18s/it]

📝 Query: چنانچه خواهان در بخش هزینه دادرسی دادخواست ناقص تقدیم کند و در پی اخطار رفع نقص ...
🔍 روش انتخاب شده: Semantic search
🔍 Semantic only: 24 نتیجه
   ✓ Retrieved: 24 documents
🔄 Reranking 24 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 31%|███       | 37/119 [12:51<20:44, 15.18s/it]

   ⚠️ [Critic] needs_revision=true but no valid citation → forcing false
[Q38] pred=3 | conf=5

 32%|███▏      | 38/119 [12:51<19:24, 14.38s/it]

📝 Query: چنانچه میان دادگاه عمومی حقوقی و دادگاه کیفری دو از یک استان اختلاف در صلاحیت رخ...
🔍 روش انتخاب شده: Semantic search
🔍 Semantic only: 24 نتیجه
   ✓ Retrieved: 24 documents
🔄 Reranking 24 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 32%|███▏      | 38/119 [13:04<19:24, 14.38s/it]

   ⚠️ [Critic] needs_revision=true but no valid citation → forcing false
[Q39] pred=3 | conf=5

 33%|███▎      | 39/119 [13:04<18:49, 14.11s/it]

📝 Query: دعوایی علیه سه نفر به اسامی شخص «الف» و شخص «ب» و شخص «ج» به خواسته 30 میلیارد ر...
🎯 روش انتخاب شده: Metadata-aware
🎯 Metadata: law='None' | اصل نمی شود
🔍 Semantic fallback...
✅ نهایی: 20 نتیجه
   ✓ Retrieved: 20 documents
🔄 Reranking 20 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 33%|███▎      | 39/119 [13:19<18:49, 14.11s/it]

   ⚠️ [Critic] needs_revision=true but no valid citation → forcing false
[Q40] pred=2 | conf=5

 34%|███▎      | 40/119 [13:20<19:05, 14.50s/it]

📝 Query: ضمانت اجرای عدم مطالبه باقیمانده مبلغ اسمی سهام در شرکت سهامی از سوی مدیران شرکت...
🔍 روش انتخاب شده: Semantic search
🔍 Semantic only: 24 نتیجه
   ✓ Retrieved: 24 documents
🔄 Reranking 24 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 34%|███▎      | 40/119 [13:32<19:05, 14.50s/it]

   ⚠️ [Critic] needs_revision=true but no valid citation → forcing false
[Q41] pred=1 | conf=5

 34%|███▍      | 41/119 [13:32<18:06, 13.93s/it]

📝 Query: در خصوص انتخاب یک شخص اصالتاً یا به نمایندگی از شخص حقوقی در ترکیب هیئت مدیره چن...
🎯 روش انتخاب شده: Metadata-aware
🎯 Metadata: law='قانون ممنوعیت دولت از مذاکره و عقد قرارداد راجع به امتیاز نفت با خارجی‌ها' | None None
🔍 فیلتر فقط قانون...
   ✓ 0 سند (law_only)
🔍 Semantic fallback...
✅ نهایی: 20 نتیجه
   ✓ Retrieved: 20 documents
🔄 Reranking 20 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 34%|███▍      | 41/119 [13:46<18:06, 13.93s/it]

   ⚠️ [Critic] needs_revision=true but no valid citation → forcing false
[Q42] pred=2 | conf=5

 35%|███▌      | 42/119 [13:46<17:42, 13.80s/it]

📝 Query: اگر پس از تقسیم و خاتمه ورشکستگی مالی متعلق به ورشکسته کشف شود، تکلیف اداره تصفی...
🎯 روش انتخاب شده: Metadata-aware
🎯 Metadata: law='قانون اداره تصفیه امور ورشکستگی' | اصل فروش بین طلبکاران تقسیم می شود
🔍 فیلتر قانون + شماره (با Range)...
   ✓ 10 سند (law+principle_number)
🔍 فیلتر فقط قانون...
   ✓ 10 سند (law_only)
🔍 Semantic fallback...
✅ نهایی: 24 نتیجه
   ✓ Retrieved: 24 documents
🎯 10 نتیجه law+article یافت شد
   ✓ Reranked: top 6 documents

 35%|███▌      | 42/119 [14:00<17:42, 13.80s/it]

   ⚠️ [Critic] needs_revision=true but no valid citation → forcing false
[Q43] pred=1 | conf=5

 36%|███▌      | 43/119 [14:00<17:33, 13.86s/it]

📝 Query: اثر ثبت نام اشخاص در دفتر ثبت تجاری چیست؟

گزینه‌ها:
1) به طور قطعی و غیر قابل ا...
🔍 روش انتخاب شده: Semantic search
🔍 Semantic only: 24 نتیجه
   ✓ Retrieved: 24 documents
🔄 Reranking 24 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 36%|███▌      | 43/119 [14:12<17:33, 13.86s/it]

   ⚠️ [Critic] needs_revision=true but no valid citation → forcing false
[Q44] pred=3 | conf=5

 37%|███▋      | 44/119 [14:12<16:52, 13.50s/it]

📝 Query: کدام مورد در خصوص «اضافه ارزش سهام» که هنگام افزایش سرمایه شرکت سهامی دریافت می ...
🔍 روش انتخاب شده: Semantic search
🔍 Semantic only: 24 نتیجه
   ✓ Retrieved: 24 documents
🔄 Reranking 24 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 37%|███▋      | 44/119 [14:24<16:52, 13.50s/it]

   ⚠️ [Critic] needs_revision=true but no valid citation → forcing false
[Q45] pred=4 | conf=5

 38%|███▊      | 45/119 [14:24<15:53, 12.89s/it]

📝 Query: در خصوص مسئولیت حقوقی دلالی که در نفس معامله منتفع میباشد و این موضوع را به طرف ...
🔍 روش انتخاب شده: Semantic search
🔍 Semantic only: 24 نتیجه
   ✓ Retrieved: 24 documents
🔄 Reranking 24 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 38%|███▊      | 45/119 [14:36<15:53, 12.89s/it]

   ⚠️ [Critic] needs_revision=true but no valid citation → forcing false
[Q46] pred=1 | conf=5

 39%|███▊      | 46/119 [14:37<15:37, 12.84s/it]

📝 Query: مطابق مقررات قانون تجارت در خصوص مفقودی برات کدام یک از موارد زیر اصولاً نیازی ب...
🎯 روش انتخاب شده: Metadata-aware
🎯 Metadata: law='قانون تجارت' | None None
🔍 فیلتر فقط قانون...
   ✓ 10 سند (law_only)
🔍 Semantic fallback...
✅ نهایی: 22 نتیجه
   ✓ Retrieved: 22 documents
🔄 Reranking 22 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 39%|███▊      | 46/119 [14:48<15:37, 12.84s/it]

   ⚠️ [Critic] needs_revision=true but no valid citation → forcing false
[Q47] pred=2 | conf=5

 39%|███▉      | 47/119 [14:48<14:54, 12.42s/it]

📝 Query: در صورتی که به موجب تصمیم مجمع عمومی عادی شخصی که کارمند رسمی دولت است به عنوان ...
🎯 روش انتخاب شده: Metadata-aware
🎯 Metadata: law='آیین‌نامه اجرای مفاد اسناد رسمی لازم‌الاجراء و طرز رسیدگی به شکایت از عملیات اجرایی' | None None
🔍 فیلتر فقط قانون...
   ✓ 0 سند (law_only)
🔍 Semantic fallback...
✅ نهایی: 20 نتیجه
   ✓ Retrieved: 20 documents
🔄 Reranking 20 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 39%|███▉      | 47/119 [20:19<14:54, 12.42s/it]

   ⚠️ [Critic] needs_revision=true but no valid citation → forcing false
[Q48] pred=3 | conf=5

 40%|████      | 48/119 [20:20<2:07:56, 108.12s/it]

📝 Query: در صورتی که مجمع عمومی عادی به طور فوق العاده شرکت سهامی، بازرس اصلی شرکت را بدو...
🔍 روش انتخاب شده: Semantic search
🔍 Semantic only: 24 نتیجه
   ✓ Retrieved: 24 documents
🔄 Reranking 24 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 40%|████      | 48/119 [20:40<2:07:56, 108.12s/it]

   ⚠️ [Critic] needs_revision=true but no valid citation → forcing false
[Q49] pred=1 | conf=5

 41%|████      | 49/119 [20:40<1:35:38, 81.98s/it]

📝 Query: کدام مورد در خصوص تبدیل شرکت تجاری موجود به نوع دیگر در حقوق موضوعه ایران، صحیح ...
🎯 روش انتخاب شده: Metadata-aware
🎯 Metadata: law='قانون تجارت' | None None
🔍 فیلتر فقط قانون...
   ✓ 10 سند (law_only)
🔍 Semantic fallback...
✅ نهایی: 22 نتیجه
   ✓ Retrieved: 22 documents
🔄 Reranking 22 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 41%|████      | 49/119 [21:08<1:35:38, 81.98s/it]

   ⚠️ [Critic] needs_revision=true but no valid citation → forcing false
[Q50] pred=2 | conf=4

 42%|████▏     | 50/119 [21:08<1:15:24, 65.57s/it]

📝 Query: برای انتشار اعلامیه پذیره نویسی یک شرکت سهامی عام با سرمایه  20میلیارد ریال کدام...
🎯 روش انتخاب شده: Metadata-aware
🎯 Metadata: law='قانون بازار اوراق بهادار' | None None
🔍 فیلتر فقط قانون...
   ✓ 10 سند (law_only)
🔍 Semantic fallback...
✅ نهایی: 24 نتیجه
   ✓ Retrieved: 24 documents
🔄 Reranking 24 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 42%|████▏     | 50/119 [21:28<1:15:24, 65.57s/it]

   ⚠️ [Critic] needs_revision=true but no valid citation → forcing false
[Q51] pred=3 | conf=5

 43%|████▎     | 51/119 [21:29<59:04, 52.13s/it]

📝 Query: کدام مورد در خصوص تأثیر متقابل ورشکستگی شرکت تجاری و شریک شرکت، صحیح است؟

گزینه...
🔍 روش انتخاب شده: Semantic search
🔍 Semantic only: 24 نتیجه
   ✓ Retrieved: 24 documents
🔄 Reranking 24 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 43%|████▎     | 51/119 [22:07<59:04, 52.13s/it]

   ⚠️ [Critic] needs_revision=true but no valid citation → forcing false
[Q52] pred=2 | conf=4

 44%|████▎     | 52/119 [22:07<53:36, 48.01s/it]

📝 Query: در مبایعه نامه ای شرط شده است که چک شماره فلان بابت قسط آخر ثمن معامله پس از انت...
🔍 روش انتخاب شده: Semantic search
🔍 Semantic only: 24 نتیجه
   ✓ Retrieved: 24 documents
🔄 Reranking 24 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 44%|████▎     | 52/119 [22:21<53:36, 48.01s/it]

   ⚠️ [Critic] needs_revision=true but no valid citation → forcing false
[Q53] pred=2 | conf=4

 45%|████▍     | 53/119 [22:21<41:46, 37.98s/it]

📝 Query: کدام مورد در خصوص احکام قانونی چک صحیح نیست؟

گزینه‌ها:
1) در صورتی که چک از طرف...
🎯 روش انتخاب شده: Metadata-aware
🎯 Metadata: law='None' | ماده 318
🔍 Semantic fallback...
✅ نهایی: 20 نتیجه
   ✓ Retrieved: 20 documents
🔄 Reranking 20 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 45%|████▍     | 53/119 [22:42<41:46, 37.98s/it]

   ⚠️ [Critic] needs_revision=true but no valid citation → forcing false
[Q54] pred=2 | conf=5

 45%|████▌     | 54/119 [22:42<35:23, 32.67s/it]

📝 Query: کدام مورد در خصوص چک صیادی که منجر به صدور گواهی عدم پرداخت شده صحیح نیست؟

گزین...
🔍 روش انتخاب شده: Semantic search
🔍 Semantic only: 24 نتیجه
   ✓ Retrieved: 24 documents
🔄 Reranking 24 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 45%|████▌     | 54/119 [22:58<35:23, 32.67s/it]

   ⚠️ [Critic] needs_revision=true but no valid citation → forcing false
[Q55] pred=3 | conf=5

 46%|████▌     | 55/119 [22:58<29:44, 27.88s/it]

📝 Query: کدام مورد در خصوص حکم ورشکستگی صحیح نیست؟

گزینه‌ها:
1) با صدور حکم ورشکستگی دعا...
🔍 روش انتخاب شده: Semantic search
🔍 Semantic only: 24 نتیجه
   ✓ Retrieved: 24 documents
🔄 Reranking 24 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 46%|████▌     | 55/119 [23:16<29:44, 27.88s/it]

   ⚠️ [Critic] needs_revision=true but no valid citation → forcing false
[Q56] pred=2 | conf=5

 47%|████▋     | 56/119 [23:16<25:58, 24.74s/it]

📝 Query: کدام یک از اعمال حقوقی تاجر ورشکسته پس از صدور حکم ورشکستگی نافذ نیست؟

گزینه‌ها...
🔍 روش انتخاب شده: Semantic search
🔍 Semantic only: 24 نتیجه
   ✓ Retrieved: 24 documents
🔄 Reranking 24 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 47%|████▋     | 56/119 [23:41<25:58, 24.74s/it]

   ⚠️ [Critic] needs_revision=true but no valid citation → forcing false
[Q57] pred=2 | conf=5

 48%|████▊     | 57/119 [23:42<25:53, 25.06s/it]

📝 Query: سند تجاری به مبلغ ده میلیون ریال صادر شده است و در ظهر آن مبلغ سند توسط صادر کنن...
🔍 روش انتخاب شده: Semantic search
🔍 Semantic only: 24 نتیجه
   ✓ Retrieved: 24 documents
🔄 Reranking 24 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 48%|████▊     | 57/119 [23:58<25:53, 25.06s/it]

   ⚠️ [Critic] needs_revision=true but no valid citation → forcing false
[Q58] pred=4 | conf=5

 49%|████▊     | 58/119 [23:58<22:47, 22.42s/it]

📝 Query: کدام مورد در خصوص گواهینامه موقت سهم، صحیح است؟

گزینه‌ها:
1) مادامی که شرکت سها...
🔍 روش انتخاب شده: Semantic search
🔍 Semantic only: 24 نتیجه
   ✓ Retrieved: 24 documents
🔄 Reranking 24 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 49%|████▊     | 58/119 [24:18<22:47, 22.42s/it]

   ⚠️ [Critic] needs_revision=true but no valid citation → forcing false
[Q59] pred=2 | conf=5

 50%|████▉     | 59/119 [24:18<21:37, 21.63s/it]

📝 Query: پس از انتشار صورت مطالبات تصدیق شده توسط اداره تصفیه طلبکاران چه اقدامی می توانن...
🎯 روش انتخاب شده: Metadata-aware
🎯 Metadata: law='قانون اداره تصفیه امور ورشکستگی' | None None
🔍 فیلتر فقط قانون...
   ✓ 10 سند (law_only)
🔍 Semantic fallback...
✅ نهایی: 24 نتیجه
   ✓ Retrieved: 24 documents
🔄 Reranking 24 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 50%|████▉     | 59/119 [24:35<21:37, 21.63s/it]

   ⚠️ [Critic] needs_revision=true but no valid citation → forcing false
[Q60] pred=1 | conf=5

 50%|█████     | 60/119 [24:35<19:58, 20.32s/it]

📝 Query: یک فرانسوی در خاک آلمان امضای وزیر دادگستری ایران را جعل میکند و در آلمان از آن ...
🎯 روش انتخاب شده: Metadata-aware
🎯 Metadata: law='قانون کاهش مجازات حبس تعزیری' | None None
🔍 فیلتر فقط قانون...
   ✓ 10 سند (law_only)
🔍 Semantic fallback...
✅ نهایی: 24 نتیجه
   ✓ Retrieved: 24 documents
🔄 Reranking 24 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 50%|█████     | 60/119 [25:13<19:58, 20.32s/it]

   ⚠️ [Critic] needs_revision=true but no valid citation → forcing false
[Q81] pred=1 | conf=3

 51%|█████▏    | 61/119 [25:13<24:48, 25.66s/it]

📝 Query: سربازی در جبهه جنگ در حالی که در محاصره دشمن ،است برای اینکه بیسیم در اختیار وی ...
🎯 روش انتخاب شده: Metadata-aware
🎯 Metadata: law='قانون حداکثر استفاده از توان تولیدی و خدماتی کشور و حمایت از کالای ایرانی' | None None
🔍 فیلتر فقط قانون...
   ✓ 10 سند (law_only)
🔍 Semantic fallback...
✅ نهایی: 24 نتیجه
   ✓ Retrieved: 24 documents
🔄 Reranking 24 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 51%|█████▏    | 61/119 [25:36<24:48, 25.66s/it]

   ⚠️ [Critic] needs_revision=true but no valid citation → forcing false
[Q82] pred=1 | conf=1

 52%|█████▏    | 62/119 [25:36<23:32, 24.78s/it]

📝 Query: کدام جرایم زیر قابل گذشت محسوب میشوند؟

گزینه‌ها:
1) خیانت در امانت و سوء استفاد...
🔍 روش انتخاب شده: Semantic search
🔍 Semantic only: 24 نتیجه
   ✓ Retrieved: 24 documents
🔄 Reranking 24 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 52%|█████▏    | 62/119 [26:07<23:32, 24.78s/it]

   ⚠️ [Critic] needs_revision=true but no valid citation → forcing false
[Q83] pred=1 | conf=5

 53%|█████▎    | 63/119 [26:07<25:02, 26.83s/it]

📝 Query: جرم غیر عمد که باعث صدمه به شخصی شده به شخصی حقوقی منتسب است. کدام مجازاتها قابل...
🎯 روش انتخاب شده: Metadata-aware
🎯 Metadata: law='قانون مجازات اشخاصی که برای بردن مال غیر تبانی می‌نمایند' | None None
🔍 فیلتر فقط قانون...
   ✓ 0 سند (law_only)
🔍 Semantic fallback...
✅ نهایی: 20 نتیجه
   ✓ Retrieved: 20 documents
🔄 Reranking 20 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 53%|█████▎    | 63/119 [26:27<25:02, 26.83s/it]

   ⚠️ [Critic] needs_revision=true but no valid citation → forcing false
[Q84] pred=4 | conf=5

 54%|█████▍    | 64/119 [26:27<22:32, 24.58s/it]

📝 Query: کدام مورد در خصوص مجازاتهای تکمیلی و تبعی، صحیح است؟

گزینه‌ها:
1) عفو خصوصی مجا...
🎯 روش انتخاب شده: Metadata-aware
🎯 Metadata: law='قانون مجازات اعمال نفوذ برخلاف حق و مقررات قانونی' | None None
🔍 فیلتر فقط قانون...
   ✓ 0 سند (law_only)
🔍 Semantic fallback...
✅ نهایی: 20 نتیجه
   ✓ Retrieved: 20 documents
🔄 Reranking 20 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 54%|█████▍    | 64/119 [26:47<22:32, 24.58s/it]

   ⚠️ [Critic] needs_revision=true but no valid citation → forcing false
[Q85] pred=3 | conf=4

 55%|█████▍    | 65/119 [26:47<20:59, 23.32s/it]

📝 Query: کدام مجازات تعزیری زیر در مقام تخفیف قابل تبدیل به مجازات دیگر نیست؟

گزینه‌ها:
...
🎯 روش انتخاب شده: Metadata-aware
🎯 Metadata: law='قانون کاهش مجازات حبس تعزیری' | None None
🔍 فیلتر فقط قانون...
   ✓ 10 سند (law_only)
🔍 Semantic fallback...
✅ نهایی: 24 نتیجه
   ✓ Retrieved: 24 documents
🔄 Reranking 24 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 55%|█████▍    | 65/119 [27:06<20:59, 23.32s/it]

   ⚠️ [Critic] needs_revision=true but no valid citation → forcing false
[Q86] pred=2 | conf=4

 55%|█████▌    | 66/119 [27:06<19:31, 22.10s/it]

📝 Query: – در صورت وجود سابقه محکومیت کیفری مؤثر فرد از کدام نهاد میتواند برخوردار شود؟

...
🔍 روش انتخاب شده: Semantic search
🔍 Semantic only: 24 نتیجه
   ✓ Retrieved: 24 documents
🔄 Reranking 24 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 55%|█████▌    | 66/119 [27:29<19:31, 22.10s/it]

   ⚠️ [Critic] needs_revision=true but no valid citation → forcing false
[Q87] pred=4 | conf=5

 56%|█████▋    | 67/119 [27:29<19:17, 22.27s/it]

📝 Query: در صورتی که مرتکب در مدت تعویق صدور حکم به دستورات دادگاه پایبندی کامل داشته باش...
🔍 روش انتخاب شده: Semantic search
🔍 Semantic only: 24 نتیجه
   ✓ Retrieved: 24 documents
🔄 Reranking 24 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 56%|█████▋    | 67/119 [27:54<19:17, 22.27s/it]

   ⚠️ [Critic] needs_revision=true but no valid citation → forcing false
[Q88] pred=1 | conf=3

 57%|█████▋    | 68/119 [27:54<19:37, 23.10s/it]

📝 Query: مجازات معاون در اسیدپاشی چه مقدار است؟

گزینه‌ها:
1) به حبس درجه 1 یا 2 محکوم می...
🎯 روش انتخاب شده: Metadata-aware
🎯 Metadata: law='قانون تشدید مجازات اسیدپاشی و حمایت از بزه‌دیدگان ناشی از آن' | None None
🔍 فیلتر فقط قانون...
   ✓ 7 سند (law_only)
🔍 Semantic fallback...
✅ نهایی: 24 نتیجه
   ✓ Retrieved: 24 documents
🔄 Reranking 24 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 57%|█████▋    | 68/119 [28:10<19:37, 23.10s/it]

   ⚠️ [Critic] needs_revision=true but no valid citation → forcing false
[Q90] pred=3 | conf=5

 58%|█████▊    | 69/119 [28:10<17:33, 21.06s/it]

📝 Query: «الف» مبادرت به حفاری و کاوش به قصد به دست آوردن اموال تاریخی مینماید لیکن هیچ م...
🔍 روش انتخاب شده: Semantic search
🔍 Semantic only: 24 نتیجه
   ✓ Retrieved: 24 documents
🔄 Reranking 24 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 58%|█████▊    | 69/119 [28:26<17:33, 21.06s/it]

   ⚠️ [Critic] needs_revision=true but no valid citation → forcing false
[Q91] pred=4 | conf=5

 59%|█████▉    | 70/119 [28:27<16:00, 19.60s/it]

📝 Query: فردی   نسبت به پلاک  ثبت ی متعلق به منابع طبیع ی  درخواست آگه ی  ثبت ی  میکند کا...
🎯 روش انتخاب شده: Metadata-aware
🎯 Metadata: law='لایحه قانونی راجع به اشتباهات ثبتی و اسناد مالکیت معارض' | None None
🔍 فیلتر فقط قانون...
   ✓ 0 سند (law_only)
🔍 Semantic fallback...
✅ نهایی: 20 نتیجه
   ✓ Retrieved: 20 documents
🔄 Reranking 20 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 59%|█████▉    | 70/119 [29:09<16:00, 19.60s/it]

   ⚠️ [Critic] needs_revision=true but no valid citation → forcing false
[Q92] pred=2 | conf=5

 60%|█████▉    | 71/119 [29:09<21:11, 26.50s/it]

📝 Query: – «الف» قصد کشتن «ب» را که محقون الدم است دارد. تیر «الف» کمانه کرده و به «ج» اص...
🔍 روش انتخاب شده: Semantic search
🔍 Semantic only: 24 نتیجه
   ✓ Retrieved: 24 documents
🔄 Reranking 24 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 60%|█████▉    | 71/119 [29:42<21:11, 26.50s/it]

   ⚠️ [Critic] needs_revision=true but no valid citation → forcing false
[Q93] pred=4 | conf=5

 61%|██████    | 72/119 [29:43<22:21, 28.54s/it]

📝 Query: – «الف» بدافزاری تولید کرده که کارایی ظاهری آن ضبط صدا است ولیکن پس از نصب تمام ...
🎯 روش انتخاب شده: Metadata-aware
🎯 Metadata: law='قانون جرایم رایانه‌ای' | None None
🔍 فیلتر فقط قانون...
   ✓ 10 سند (law_only)
🔍 Semantic fallback...
✅ نهایی: 24 نتیجه
   ✓ Retrieved: 24 documents
🔄 Reranking 24 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 61%|██████    | 72/119 [29:59<22:21, 28.54s/it]

   ⚠️ [Critic] needs_revision=true but no valid citation → forcing false
[Q94] pred=3 | conf=5

 61%|██████▏   | 73/119 [29:59<19:09, 24.99s/it]

📝 Query: «الف» مبادرت به انعقاد قراردادی برای انجام کاری با «ب» مینماید و مبلغ یک میلیارد...
🔍 روش انتخاب شده: Semantic search
🔍 Semantic only: 24 نتیجه
   ✓ Retrieved: 24 documents
🔄 Reranking 24 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 61%|██████▏   | 73/119 [30:30<19:09, 24.99s/it]

   ⚠️ [Critic] needs_revision=true but no valid citation → forcing false
[Q95] pred=1 | conf=4

 62%|██████▏   | 74/119 [30:30<20:07, 26.83s/it]

📝 Query: قاضی دادگاه در جلسه رسیدگی از کارشناس رسمی دادگستری برای رفع ابهام میزان خسارت و...
🎯 روش انتخاب شده: Metadata-aware
🎯 Metadata: law='آیین‌نامه اجرای مفاد اسناد رسمی لازم‌الاجراء و طرز رسیدگی به شکایت از عملیات اجرایی' | None None
🔍 فیلتر فقط قانون...
   ✓ 0 سند (law_only)
🔍 Semantic fallback...
✅ نهایی: 20 نتیجه
   ✓ Retrieved: 20 documents
🔄 Reranking 20 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 62%|██████▏   | 74/119 [30:57<20:07, 26.83s/it]

   ⚠️ [Critic] needs_revision=true but no valid citation → forcing false
[Q96] pred=2 | conf=4

 63%|██████▎   | 75/119 [30:57<19:40, 26.83s/it]

📝 Query: بر کدام یک از اشخاص زیر مجازات کلاهبرداری اعمال نمی شود؟

گزینه‌ها:
1) اشخاصی که...
🎯 روش انتخاب شده: Metadata-aware
🎯 Metadata: law='قانون مجازات اشخاصی که برای بردن مال غیر تبانی می‌نمایند' | None None
🔍 فیلتر فقط قانون...
   ✓ 0 سند (law_only)
🔍 Semantic fallback...
✅ نهایی: 20 نتیجه
   ✓ Retrieved: 20 documents
🔄 Reranking 20 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 63%|██████▎   | 75/119 [31:18<19:40, 26.83s/it]

   ⚠️ [Critic] needs_revision=true but no valid citation → forcing false
[Q97] pred=2 | conf=5

 64%|██████▍   | 76/119 [31:18<18:01, 25.15s/it]

📝 Query: آقای «الف» نماینده قانونی شرکت »ب« به جهت تسهیل در اخذ وام دولتی مرتکب رشا با مج...
🎯 روش انتخاب شده: Metadata-aware
🎯 Metadata: law='قانون کاهش مجازات حبس تعزیری' | None None
🔍 فیلتر فقط قانون...
   ✓ 10 سند (law_only)
🔍 Semantic fallback...
✅ نهایی: 24 نتیجه
   ✓ Retrieved: 24 documents
🔄 Reranking 24 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 64%|██████▍   | 76/119 [31:35<18:01, 25.15s/it]

   ⚠️ [Critic] needs_revision=true but no valid citation → forcing false
[Q98] pred=4 | conf=5

 65%|██████▍   | 77/119 [31:35<15:53, 22.71s/it]

📝 Query: پسر شانزده ساله ای مرتکب جرم ضرب و جرح عمدی با مجازات تعزیری درجه  6 شده است. دا...
🎯 روش انتخاب شده: Metadata-aware
🎯 Metadata: law='قانون کاهش مجازات حبس تعزیری' | None None
🔍 فیلتر فقط قانون...
   ✓ 10 سند (law_only)
🔍 Semantic fallback...
✅ نهایی: 24 نتیجه
   ✓ Retrieved: 24 documents
🔄 Reranking 24 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 65%|██████▍   | 77/119 [32:05<15:53, 22.71s/it]

   ⚠️ [Critic] needs_revision=true but no valid citation → forcing false
[Q99] pred=4 | conf=5

 66%|██████▌   | 78/119 [32:05<16:56, 24.79s/it]

📝 Query: مردی با جعل سند ملک همسر خود را به عنوان مال خود معرفی و این سند مجعول را به پسر...
🎯 روش انتخاب شده: Metadata-aware
🎯 Metadata: law='قانون آیین دادرسی کیفری' | None None
🔍 فیلتر فقط قانون...
   ✓ 10 سند (law_only)
🔍 Semantic fallback...
✅ نهایی: 24 نتیجه
   ✓ Retrieved: 24 documents
🔄 Reranking 24 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 66%|██████▌   | 78/119 [32:22<16:56, 24.79s/it]

   ⚠️ [Critic] needs_revision=true but no valid citation → forcing false
[Q100] pred=1 | conf=2

 66%|██████▋   | 79/119 [32:22<15:03, 22.58s/it]

📝 Query: رسیدگی به جرم قتل غیر عمدی ناشی از تصادفات رانندگی و صدور حکم در خصوص این جرم در...
🎯 روش انتخاب شده: Metadata-aware
🎯 Metadata: law='قانون رسیدگی به تخلفات رانندگی' | None None
🔍 فیلتر فقط قانون...
   ✓ 0 سند (law_only)
🔍 Semantic fallback...
✅ نهایی: 19 نتیجه
   ✓ Retrieved: 19 documents
🔄 Reranking 19 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 66%|██████▋   | 79/119 [32:41<15:03, 22.58s/it]

   ⚠️ [Critic] needs_revision=true but no valid citation → forcing false
[Q101] pred=2 | conf=5

 67%|██████▋   | 80/119 [32:41<13:54, 21.40s/it]

📝 Query: کدام مورد در خصوص آرای اصداری راجع به جنبه عمومی جرایم غیر عمدی ناشی از کار، صحی...
🎯 روش انتخاب شده: Metadata-aware
🎯 Metadata: law='قانون مجازات راجع به انتقال مال غیر' | None None
🔍 فیلتر فقط قانون...
   ✓ 0 سند (law_only)
🔍 Semantic fallback...
✅ نهایی: 20 نتیجه
   ✓ Retrieved: 20 documents
🔄 Reranking 20 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 67%|██████▋   | 80/119 [33:00<13:54, 21.40s/it]

   ⚠️ [Critic] needs_revision=true but no valid citation → forcing false
[Q102] pred=1 | conf=5

 68%|██████▊   | 81/119 [33:00<13:07, 20.74s/it]

📝 Query: در کدام یک از جرایم زیر امکان جلب مطلق و بدون شرط متهم پرونده بدون ارسال احضاریه...
🔍 روش انتخاب شده: Semantic search
🔍 Semantic only: 24 نتیجه
   ✓ Retrieved: 24 documents
🔄 Reranking 24 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 68%|██████▊   | 81/119 [33:24<13:07, 20.74s/it]

   ⚠️ [Critic] needs_revision=true but no valid citation → forcing false
[Q103] pred=4 | conf=5

 69%|██████▉   | 82/119 [33:24<13:17, 21.57s/it]

📝 Query: مرجع حل اختلاف در صلاحیت بین دادگاه کیفری دو و دادگاه حقوقی واقع در حوزه قضایی ی...
🔍 روش انتخاب شده: Semantic search
🔍 Semantic only: 24 نتیجه
   ✓ Retrieved: 24 documents
🔄 Reranking 24 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 69%|██████▉   | 82/119 [33:52<13:17, 21.57s/it]

   ⚠️ [Critic] needs_revision=true but no valid citation → forcing false
[Q104] pred=1 | conf=5

 70%|██████▉   | 83/119 [33:52<14:06, 23.52s/it]

📝 Query: چنانچه ضابط دادگستری فاقد کارت ویژه ضابطان در ارتباط با جرایم مشهود یا در راستای...
🔍 روش انتخاب شده: Semantic search
🔍 Semantic only: 24 نتیجه
   ✓ Retrieved: 24 documents
🔄 Reranking 24 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 70%|██████▉   | 83/119 [34:08<14:06, 23.52s/it]

   ⚠️ [Critic] needs_revision=true but no valid citation → forcing false
[Q105] pred=1 | conf=5

 71%|███████   | 84/119 [34:08<12:25, 21.31s/it]

📝 Query: در جرایم غیر قابل گذشت چنانچه پس از صدور کیفرخواست و قبل از ارسال به دادگاه، شاک...
🔍 روش انتخاب شده: Semantic search
🔍 Semantic only: 24 نتیجه
   ✓ Retrieved: 24 documents
🔄 Reranking 24 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 71%|███████   | 84/119 [34:38<12:25, 21.31s/it]

   ⚠️ [Critic] needs_revision=true but no valid citation → forcing false
[Q106] pred=3 | conf=5

 71%|███████▏  | 85/119 [34:38<13:31, 23.88s/it]

📝 Query: کدام مورد در خصوص تبعیت دادگاه رسیدگی کننده به امور حقوقی یا ضرر و زیان ناشی از ...
🔍 روش انتخاب شده: Semantic search
🔍 Semantic only: 24 نتیجه
   ✓ Retrieved: 24 documents
🔄 Reranking 24 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 71%|███████▏  | 85/119 [34:54<13:31, 23.88s/it]

   ⚠️ [Critic] needs_revision=true but no valid citation → forcing false
[Q107] pred=2 | conf=5

 72%|███████▏  | 86/119 [34:55<11:55, 21.70s/it]

📝 Query: در کدام یک از جرایم مشهود زیر در صورت عدم حضور ضابطان دادگستری شهروندان نمی توان...
🎯 روش انتخاب شده: Metadata-aware
🎯 Metadata: law='قانون مجازات اشخاصی که برای بردن مال غیر تبانی می‌نمایند' | None None
🔍 فیلتر فقط قانون...
   ✓ 0 سند (law_only)
🔍 Semantic fallback...
✅ نهایی: 20 نتیجه
   ✓ Retrieved: 20 documents
🔄 Reranking 20 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 72%|███████▏  | 86/119 [35:11<11:55, 21.70s/it]

   ⚠️ [Critic] needs_revision=true but no valid citation → forcing false
[Q108] pred=4 | conf=4

 73%|███████▎  | 87/119 [35:11<10:47, 20.23s/it]

📝 Query: کدام یک از قرارهای دادیار باید در همان روز صدور به نظر دادستان برسد؟

گزینه‌ها:
...
🔍 روش انتخاب شده: Semantic search
🔍 Semantic only: 24 نتیجه
   ✓ Retrieved: 24 documents
🔄 Reranking 24 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 73%|███████▎  | 87/119 [35:27<10:47, 20.23s/it]

   ⚠️ [Critic] needs_revision=true but no valid citation → forcing false
[Q109] pred=1 | conf=5

 74%|███████▍  | 88/119 [35:28<09:49, 19.02s/it]

📝 Query: – ضبط اموال یا اشیا از اختیارات کدام مرجع قضایی است؟

گزینه‌ها:
1) دادگاه | 2) ح...
🔍 روش انتخاب شده: Semantic search
🔍 Semantic only: 24 نتیجه
   ✓ Retrieved: 24 documents
🔄 Reranking 24 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 74%|███████▍  | 88/119 [36:00<09:49, 19.02s/it]

   ⚠️ [Critic] needs_revision=true but no valid citation → forcing false
[Q110] pred=1 | conf=5

 75%|███████▍  | 89/119 [36:00<11:30, 23.02s/it]

📝 Query: اگر دختر 15 سالهای مرتکب جرم تعزیری درجه سه در صلاحیت ذاتی دادگاه انقلاب شود جهت...
🎯 روش انتخاب شده: Metadata-aware
🎯 Metadata: law='قانون حمایت از اطفال و نوجوانان' | None None
🔍 فیلتر فقط قانون...
   ✓ 0 سند (law_only)
🔍 Semantic fallback...
✅ نهایی: 20 نتیجه
   ✓ Retrieved: 20 documents
🔄 Reranking 20 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 75%|███████▍  | 89/119 [36:21<11:30, 23.02s/it]

   ⚠️ [Critic] needs_revision=true but no valid citation → forcing false
[Q111] pred=2 | conf=5

 76%|███████▌  | 90/119 [36:21<10:51, 22.45s/it]

📝 Query: کدام مورد در خصوص قرار عدم صلاحیت اصداری از دادگاه کیفری یک صحیح است؟

گزینه‌ها:...
🔍 روش انتخاب شده: Semantic search
🔍 Semantic only: 24 نتیجه
   ✓ Retrieved: 24 documents
🔄 Reranking 24 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 76%|███████▌  | 90/119 [36:37<10:51, 22.45s/it]

   ⚠️ [Critic] needs_revision=true but no valid citation → forcing false
[Q112] pred=2 | conf=5

 76%|███████▋  | 91/119 [36:37<09:32, 20.43s/it]

📝 Query: ابتلای به جنون محکوم علیه در جرایم تعزیری پس از صدور حکم قطعی چه تأثیری بر اجرای...
🎯 روش انتخاب شده: Metadata-aware
🎯 Metadata: law='قانون اجرای احکام مدنی' | None None
🔍 فیلتر فقط قانون...
   ✓ 10 سند (law_only)
🔍 Semantic fallback...
✅ نهایی: 24 نتیجه
   ✓ Retrieved: 24 documents
🔄 Reranking 24 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 76%|███████▋  | 91/119 [36:57<09:32, 20.43s/it]

   ⚠️ [Critic] needs_revision=true but no valid citation → forcing false
[Q113] pred=1 | conf=2

 77%|███████▋  | 92/119 [36:58<09:15, 20.57s/it]

📝 Query: تعیین وکیل تسخیری برای اطفال و نوجوانان در کدام یک از جرایم الزامی نیست؟

گزینه‌...
🎯 روش انتخاب شده: Metadata-aware
🎯 Metadata: law='قانون حمایت از اطفال و نوجوانان' | None None
🔍 فیلتر فقط قانون...
   ✓ 0 سند (law_only)
🔍 Semantic fallback...
✅ نهایی: 20 نتیجه
   ✓ Retrieved: 20 documents
🔄 Reranking 20 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 77%|███████▋  | 92/119 [37:15<09:15, 20.57s/it]

   ⚠️ [Critic] needs_revision=true but no valid citation → forcing false
[Q114] pred=3 | conf=5

 78%|███████▊  | 93/119 [37:15<08:29, 19.61s/it]

📝 Query: کدام مورد در خصوص صدور قرار کفالت و وثیقه در جرایم غیر عمدی، صحیح است؟

گزینه‌ها...
🔍 روش انتخاب شده: Semantic search
🔍 Semantic only: 24 نتیجه
   ✓ Retrieved: 24 documents
🔄 Reranking 24 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 78%|███████▊  | 93/119 [37:34<08:29, 19.61s/it]

   ⚠️ [Critic] needs_revision=true but no valid citation → forcing false
[Q115] pred=2 | conf=5

 79%|███████▉  | 94/119 [37:34<08:07, 19.50s/it]

📝 Query: در کدام یک از جرایم تعزیری زیر در صورت ارائه تضمین لازم برای جبران خسارات وارده ...
🎯 روش انتخاب شده: Metadata-aware
🎯 Metadata: law='قانون بیمه اجباری خسارات وارد شده به شخص ثالث در اثر حوادث ناشی از وسایل نقلیه' | None None
🔍 فیلتر فقط قانون...
   ✓ 0 سند (law_only)
🔍 Semantic fallback...
✅ نهایی: 20 نتیجه
   ✓ Retrieved: 20 documents
🔄 Reranking 20 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 79%|███████▉  | 94/119 [37:57<08:07, 19.50s/it]

   ⚠️ [Critic] needs_revision=true but no valid citation → forcing false
[Q116] pred=4 | conf=5

 80%|███████▉  | 95/119 [37:58<08:16, 20.67s/it]

📝 Query: کدام مورد در خصوص سوگند به عنوان یکی از ادله اثبات در امور کیفری، صحیح نیست؟

گز...
🔍 روش انتخاب شده: Semantic search
🔍 Semantic only: 24 نتیجه
   ✓ Retrieved: 24 documents
🔄 Reranking 24 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 80%|███████▉  | 95/119 [38:20<08:16, 20.67s/it]

   ⚠️ [Critic] needs_revision=true but no valid citation → forcing false
[Q117] pred=3 | conf=5

 81%|████████  | 96/119 [38:20<08:07, 21.20s/it]

📝 Query: اگر فردی در کرج متهم به ارتکاب جرم تعزیری درجه دو شود و پس از رسیدگی و صدور حکم ...
🔍 روش انتخاب شده: Semantic search
🔍 Semantic only: 24 نتیجه
   ✓ Retrieved: 24 documents
🔄 Reranking 24 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 81%|████████  | 96/119 [38:42<08:07, 21.20s/it]

   ⚠️ [Critic] needs_revision=true but no valid citation → forcing false
[Q118] pred=2 | conf=5

 82%|████████▏ | 97/119 [38:42<07:52, 21.48s/it]

📝 Query: در مورد احکام قطعی راجع به حقوق عامه و دعاوی مربوط به دولت امور خیریه و اوقاف عا...
🎯 روش انتخاب شده: Metadata-aware
🎯 Metadata: law='قانون آیین دادرسی کیفری' | ماده 477
🔍 فیلتر قانون + شماره (با Range)...
   ✓ 1 سند (law+article_number)
🔍 فیلتر فقط قانون...
   ✓ 10 سند (law_only)
🔍 Semantic fallback...
✅ نهایی: 24 نتیجه
   ✓ Retrieved: 24 documents
🎯 1 نتیجه law+article یافت شد
🔄 Reranking 23 سند دیگر...
   ✓ Reranked: top 6 documents

 82%|████████▏ | 97/119 [39:00<07:52, 21.48s/it]

   ⚠️ [Critic] needs_revision=true but no valid citation → forcing false
[Q119] pred=4 | conf=5

 82%|████████▏ | 98/119 [39:00<07:10, 20.49s/it]

📝 Query: کدام مورد با آرای وحدت رویه هیئت عمومی دیوان عالی کشور و مقررات قانونی مطابقت ند...
🎯 روش انتخاب شده: Metadata-aware
🎯 Metadata: law='قانون آیین دادرسی کیفری' | None None
🔍 فیلتر فقط قانون...
   ✓ 10 سند (law_only)
🔍 Semantic fallback...
✅ نهایی: 24 نتیجه
   ✓ Retrieved: 24 documents
🔄 Reranking 24 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 82%|████████▏ | 98/119 [39:21<07:10, 20.49s/it]

   ⚠️ [Critic] needs_revision=true but no valid citation → forcing false
[Q120] pred=1 | conf=5

 83%|████████▎ | 99/119 [39:22<06:53, 20.69s/it]

📝 Query: به موجب قانون اساس ی ابتکار بودجه کل کشور با کدام مرجع است؟

گزینه‌ها:
1) دیوان ...
🎯 روش انتخاب شده: Metadata-aware
🎯 Metadata: law='قانون الحاق دولت جمهوری اسلامی ایران به کنوانسیون مواد روانگردان' | None None
🔍 فیلتر فقط قانون...
   ✓ 0 سند (law_only)
🔍 Semantic fallback...
✅ نهایی: 20 نتیجه
   ✓ Retrieved: 20 documents
🔄 Reranking 20 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 83%|████████▎ | 99/119 [39:39<06:53, 20.69s/it]

   ⚠️ [Critic] needs_revision=true but no valid citation → forcing false
[Q121] pred=2 | conf=5

 84%|████████▍ | 100/119 [39:40<06:18, 19.90s/it]

📝 Query: در قانون اساسی از کدام مورد به عنوان یکی از مصادیق انفال و ثروتهای عمومی یاد شده...
🎯 روش انتخاب شده: Metadata-aware
🎯 Metadata: law='قانون اساسی' | None None
🔍 فیلتر فقط قانون...
   ✓ 10 سند (law_only)
🔍 Semantic fallback...
✅ نهایی: 24 نتیجه
   ✓ Retrieved: 24 documents
🔄 Reranking 24 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 84%|████████▍ | 100/119 [40:00<06:18, 19.90s/it]

   ⚠️ [Critic] needs_revision=true but no valid citation → forcing false
[Q122] pred=4 | conf=5

 85%|████████▍ | 101/119 [40:00<06:01, 20.08s/it]

📝 Query: طبق قانون اساسی اعمال کدام صلاحیت رئیس قوه قضائیه پس از مشورت امکان پذیر است؟

گ...
🎯 روش انتخاب شده: Metadata-aware
🎯 Metadata: law='قانون اساسی' | None None
🔍 فیلتر فقط قانون...
   ✓ 10 سند (law_only)
🔍 Semantic fallback...
✅ نهایی: 24 نتیجه
   ✓ Retrieved: 24 documents
🔄 Reranking 24 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 85%|████████▍ | 101/119 [40:13<06:01, 20.08s/it]

   ⚠️ [Critic] needs_revision=true but no valid citation → forcing false
[Q123] pred=3 | conf=5

 86%|████████▌ | 102/119 [40:14<05:07, 18.10s/it]

📝 Query: به موجب قانون اساسی رسیدگی به کدام دعاوی زیر باید به صورت خارج از نوبت انجام گیر...
🎯 روش انتخاب شده: Metadata-aware
🎯 Metadata: law='قانون اساسی' | اصل 49
🔍 فیلتر قانون + شماره (با Range)...
   ✓ 1 سند (law+principle_number)
🔍 فیلتر فقط قانون...
   ✓ 10 سند (law_only)
🔍 Semantic fallback...
✅ نهایی: 24 نتیجه
   ✓ Retrieved: 24 documents
🎯 1 نتیجه law+article یافت شد
🔄 Reranking 23 سند دیگر...
   ✓ Reranked: top 6 documents

 86%|████████▌ | 102/119 [40:54<05:07, 18.10s/it]

   ⚠️ [Critic] needs_revision=true but no valid citation → forcing false
[Q124] pred=2 | conf=3

 87%|████████▋ | 103/119 [40:54<06:35, 24.71s/it]

📝 Query: در قانون اساسی به کدام یک از اصول حاکم بر رسیدگیهای قضایی تصریح شده است؟

گزینه‌...
🎯 روش انتخاب شده: Metadata-aware
🎯 Metadata: law='قانون اساسی' | None None
🔍 فیلتر فقط قانون...
   ✓ 10 سند (law_only)
🔍 Semantic fallback...
✅ نهایی: 24 نتیجه
   ✓ Retrieved: 24 documents
🔄 Reranking 24 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 87%|████████▋ | 103/119 [41:10<06:35, 24.71s/it]

   ⚠️ [Critic] needs_revision=true but no valid citation → forcing false
[Q125] pred=1 | conf=5

 87%|████████▋ | 104/119 [41:10<05:33, 22.22s/it]

📝 Query: «منع تبذیر» ذیل ضوابط حاکم بر کدام یک از شئون نظام جمهوری اسلامی در قانون اساسی ...
🎯 روش انتخاب شده: Metadata-aware
🎯 Metadata: law='قانون اساسی' | None None
🔍 فیلتر فقط قانون...
   ✓ 10 سند (law_only)
🔍 Semantic fallback...
✅ نهایی: 24 نتیجه
   ✓ Retrieved: 24 documents
🔄 Reranking 24 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 87%|████████▋ | 104/119 [41:27<05:33, 22.22s/it]

   ⚠️ [Critic] needs_revision=true but no valid citation → forcing false
[Q126] pred=2 | conf=5

 88%|████████▊ | 105/119 [41:27<04:47, 20.52s/it]

📝 Query: کدام مورد در خصوص تفویض اختیار قانونگذاری از سوی مجلس شورای اسلامی، صحیح است؟

گ...
🎯 روش انتخاب شده: Metadata-aware
🎯 Metadata: law='قانون مجازات اسلامی مصوب 1375' | None None
🔍 فیلتر فقط قانون...
   ✓ 10 سند (law_only)
🔍 Semantic fallback...
✅ نهایی: 24 نتیجه
   ✓ Retrieved: 24 documents
🔄 Reranking 24 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 88%|████████▊ | 105/119 [41:43<04:47, 20.52s/it]

   ⚠️ [Critic] needs_revision=true but no valid citation → forcing false
[Q127] pred=1 | conf=2

 89%|████████▉ | 106/119 [41:43<04:10, 19.29s/it]

📝 Query: در قانون اساسی کدام آزادی مشروط به رعایت حقوق دیگران شده است؟

گزینه‌ها:
1) آزاد...
🎯 روش انتخاب شده: Metadata-aware
🎯 Metadata: law='قانون اساسی' | None None
🔍 فیلتر فقط قانون...
   ✓ 10 سند (law_only)
🔍 Semantic fallback...
✅ نهایی: 24 نتیجه
   ✓ Retrieved: 24 documents
🔄 Reranking 24 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 89%|████████▉ | 106/119 [42:03<04:10, 19.29s/it]

   ⚠️ [Critic] needs_revision=true but no valid citation → forcing false
[Q128] pred=2 | conf=5

 90%|████████▉ | 107/119 [42:03<03:55, 19.59s/it]

📝 Query: بنا به تصریح قانون اساس ی مصوبات کدام مرجع نباید با متن و روح قانون مغایرت داشته...
🔍 روش انتخاب شده: Semantic search
🔍 Semantic only: 24 نتیجه
   ✓ Retrieved: 24 documents
🔄 Reranking 24 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 90%|████████▉ | 107/119 [42:38<03:55, 19.59s/it]

   ⚠️ [Critic] needs_revision=true but no valid citation → forcing false
[Q129] pred=3 | conf=5

 91%|█████████ | 108/119 [42:38<04:26, 24.21s/it]

📝 Query: در قانون اساسی بر ممنوعیت تبعیض در کدام مورد زیر تصریح شده است؟

گزینه‌ها:
1) دا...
🎯 روش انتخاب شده: Metadata-aware
🎯 Metadata: law='قانون اساسی' | None None
🔍 فیلتر فقط قانون...
   ✓ 10 سند (law_only)
🔍 Semantic fallback...
✅ نهایی: 24 نتیجه
   ✓ Retrieved: 24 documents
🔄 Reranking 24 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 91%|█████████ | 108/119 [43:03<04:26, 24.21s/it]

   ⚠️ [Critic] needs_revision=true but no valid citation → forcing false
[Q130] pred=2 | conf=5

 92%|█████████▏| 109/119 [43:04<04:05, 24.50s/it]

📝 Query: بنا به تصریح قانون اساسی سلب کدام یک از حقوق زیر به درخواست خود شخص ذی حق امکان ...
🎯 روش انتخاب شده: Metadata-aware
🎯 Metadata: law='قانون اساسی' | None None
🔍 فیلتر فقط قانون...
   ✓ 10 سند (law_only)
🔍 Semantic fallback...
✅ نهایی: 24 نتیجه
   ✓ Retrieved: 24 documents
🔄 Reranking 24 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 92%|█████████▏| 109/119 [43:29<04:05, 24.50s/it]

   ⚠️ [Critic] needs_revision=true but no valid citation → forcing false
[Q131] pred=1 | conf=5

 92%|█████████▏| 110/119 [43:29<03:42, 24.71s/it]

📝 Query: کدام مورد از ابعاد حق دادخواهی در قانون اساسی به شمار نمی آید؟

گزینه‌ها:
1) در ...
🎯 روش انتخاب شده: Metadata-aware
🎯 Metadata: law='قانون اساسی' | None None
🔍 فیلتر فقط قانون...
   ✓ 10 سند (law_only)
🔍 Semantic fallback...
✅ نهایی: 24 نتیجه
   ✓ Retrieved: 24 documents
🔄 Reranking 24 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 92%|█████████▏| 110/119 [43:47<03:42, 24.71s/it]

   ⚠️ [Critic] needs_revision=true but no valid citation → forcing false
[Q132] pred=3 | conf=5

 93%|█████████▎| 111/119 [43:47<03:02, 22.80s/it]

📝 Query: شهروندی که از مصوبه دولت متضرر شده و آن را خلاف قانون میداند همزمان نسبت به مصوب...
🎯 روش انتخاب شده: Metadata-aware
🎯 Metadata: law='قانون اساسی' | اصل 90
🔍 فیلتر قانون + شماره (با Range)...
   ✓ 1 سند (law+principle_number)
🔍 فیلتر فقط قانون...
   ✓ 10 سند (law_only)
🔍 Semantic fallback...
✅ نهایی: 24 نتیجه
   ✓ Retrieved: 24 documents
🎯 1 نتیجه law+article یافت شد
🔄 Reranking 23 سند دیگر...
   ✓ Reranked: top 6 documents

 93%|█████████▎| 111/119 [45:01<03:02, 22.80s/it]

   ⚠️ [Critic] needs_revision=true but no valid citation → forcing false
[Q133] pred=2 | conf=4

 94%|█████████▍| 112/119 [45:01<04:27, 38.20s/it]

📝 Query: کدام مورد در خصوص اعمال قوه مقننه صحیح است؟

گزینه‌ها:
1) اعمال قوه مقننه در مسا...
🎯 روش انتخاب شده: Metadata-aware
🎯 Metadata: law='قانون مجازات اخلالگران در نظام اقتصادی کشور' | None None
🔍 فیلتر فقط قانون...
   ✓ 0 سند (law_only)
🔍 Semantic fallback...
✅ نهایی: 20 نتیجه
   ✓ Retrieved: 20 documents
🔄 Reranking 20 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 94%|█████████▍| 112/119 [45:19<04:27, 38.20s/it]

   ⚠️ [Critic] needs_revision=true but no valid citation → forcing false
[Q134] pred=4 | conf=5

 95%|█████████▍| 113/119 [45:19<03:12, 32.07s/it]

📝 Query: به موجب قانون اساسی کدام مورد ضرورتاً نیاز به تصویب مجلس شورای اسلامی ندارد؟

گز...
🎯 روش انتخاب شده: Metadata-aware
🎯 Metadata: law='قانون اساسی' | None None
🔍 فیلتر فقط قانون...
   ✓ 10 سند (law_only)
🔍 Semantic fallback...
✅ نهایی: 24 نتیجه
   ✓ Retrieved: 24 documents
🔄 Reranking 24 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 95%|█████████▍| 113/119 [45:32<03:12, 32.07s/it]

   ⚠️ [Critic] needs_revision=true but no valid citation → forcing false
[Q135] pred=1 | conf=5

 96%|█████████▌| 114/119 [45:32<02:12, 26.43s/it]

📝 Query: کارمند شرکت دولتی در ایامی که در مرخصی بدون حقوق به سر میبرد به عنوان مدیر عامل ...
🎯 روش انتخاب شده: Metadata-aware
🎯 Metadata: law='قانون ممنوعیت دولت از مذاکره و عقد قرارداد راجع به امتیاز نفت با خارجی‌ها' | None None
🔍 فیلتر فقط قانون...
   ✓ 0 سند (law_only)
🔍 Semantic fallback...
✅ نهایی: 20 نتیجه
   ✓ Retrieved: 20 documents
🔄 Reranking 20 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 96%|█████████▌| 114/119 [45:48<02:12, 26.43s/it]

   ⚠️ [Critic] needs_revision=true but no valid citation → forcing false
[Q136] pred=3 | conf=5

 97%|█████████▋| 115/119 [45:48<01:33, 23.37s/it]

📝 Query: شرکتی با اختراع یک دستگاه و فروش عمده آن به کارخانجات خودروسازی موجب بیکار شدن ت...
🎯 روش انتخاب شده: Metadata-aware
🎯 Metadata: law='قانون اساسی' | اصل 40
🔍 فیلتر قانون + شماره (با Range)...
   ✓ 1 سند (law+principle_number)
🔍 فیلتر فقط قانون...
   ✓ 10 سند (law_only)
🔍 Semantic fallback...
✅ نهایی: 24 نتیجه
   ✓ Retrieved: 24 documents
🎯 1 نتیجه law+article یافت شد
🔄 Reranking 23 سند دیگر...
   ✓ Reranked: top 6 documents

 97%|█████████▋| 115/119 [46:06<01:33, 23.37s/it]

   ⚠️ [Critic] needs_revision=true but no valid citation → forcing false
[Q137] pred=1 | conf=5

 97%|█████████▋| 116/119 [46:07<01:05, 21.82s/it]

📝 Query: چنانچه مجلس شورای اسلامی طی مصوبه ای تعیین تکلیف استخدام کارشناسان خارجی در وزار...
🎯 روش انتخاب شده: Metadata-aware
🎯 Metadata: law='قانون اساسی' | None None
🔍 فیلتر فقط قانون...
   ✓ 10 سند (law_only)
🔍 Semantic fallback...
✅ نهایی: 24 نتیجه
   ✓ Retrieved: 24 documents
🔄 Reranking 24 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 97%|█████████▋| 116/119 [46:20<01:05, 21.82s/it]

   ⚠️ [Critic] needs_revision=true but no valid citation → forcing false
[Q138] pred=3 | conf=5

 98%|█████████▊| 117/119 [46:20<00:38, 19.34s/it]

📝 Query: شورای اسلامی شهری اقدام به وضع مصوبه ای کرده و به موجب آن هرگونه استخدام در شورا...
🎯 روش انتخاب شده: Metadata-aware
🎯 Metadata: law='قانون اساسی' | None None
🔍 فیلتر فقط قانون...
   ✓ 10 سند (law_only)
🔍 Semantic fallback...
✅ نهایی: 24 نتیجه
   ✓ Retrieved: 24 documents
🔄 Reranking 24 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 98%|█████████▊| 117/119 [46:33<00:38, 19.34s/it]

   ⚠️ [Critic] needs_revision=true but no valid citation → forcing false
[Q139] pred=4 | conf=4

 99%|█████████▉| 118/119 [46:33<00:17, 17.27s/it]

📝 Query: در قانون اساسی به تعیین تکلیف کدام یک از امور مربوط به هیئت منصفه در جرایم سیاسی...
🎯 روش انتخاب شده: Metadata-aware
🎯 Metadata: law='قانون اساسی' | None None
🔍 فیلتر فقط قانون...
   ✓ 10 سند (law_only)
🔍 Semantic fallback...
✅ نهایی: 24 نتیجه
   ✓ Retrieved: 24 documents
🔄 Reranking 24 سند (بدون law+article)...
   ✓ Reranked: top 6 documents

 99%|█████████▉| 118/119 [46:55<00:17, 17.27s/it]

   ⚠️ [Critic] needs_revision=true but no valid citation → forcing false
[Q140] pred=4 | conf=5

100%|██████████| 119/119 [46:55<00:00, 23.66s/it]

Saved to: f:\Thesis\project\3-Multi-Agent-System\data\eval\notebook08_full_v2_results.csv
Rows in result: 119

In [23]:
df_res_v2["category"] = df_q["category"]

In [27]:
# %%
overall_acc = df_res_v2["is_correct"].mean()
coverage = df_res_v2["pred"].notna().mean()
error_rate = df_res_v2["error"].notna().mean()

print("Overall accuracy (v2):", overall_acc)
print("Coverage (has pred):", coverage)
print("Error rate:", error_rate)

print(df_res_v2.groupby("category")["is_correct"].mean())

out_path = PROJECT_ROOT / "data" / "eval" / "notebook08_full_v2_results.csv"
out_path.parent.mkdir(parents=True, exist_ok=True)
df_res_v2.to_csv(out_path, index=False, encoding="utf-8-sig")
print("Saved to:", out_path)

Overall accuracy (v2): 0.6302521008403361
Coverage (has pred): 1.0
Error rate: 0.0
category
آیین دادرسی مدنی     0.600000
آیین دادرسی کیفری    0.750000
حقوق اساسی           0.700000
حقوق تجارت           0.750000
حقوق جزا             0.315789
حقوق مدنی            0.650000
Name: is_correct, dtype: float64
Saved to: f:\Thesis\project\3-Multi-Agent-System\data\eval\notebook08_full_v2_results.csv

In [28]:
# %%
agg = df_res_v2.groupby("category").agg(
    n=("question_number", "count"),
    acc=("is_correct", "mean"),
    coverage=("pred", lambda s: s.notna().mean()),
    error_rate=("error", lambda s: s.notna().mean()),
    avg_time=("elapsed_sec", "mean"),
)
display(agg.sort_values("n", ascending=False))

                    n       acc  coverage  error_rate   avg_time
category
آیین دادرسی مدنی   20  0.600000       1.0         0.0  18.782998
آیین دادرسی کیفری  20  0.750000       1.0         0.0  20.743720
حقوق اساسی         20  0.700000       1.0         0.0  22.470579
حقوق تجارت         20  0.750000       1.0         0.0  33.556428
حقوق مدنی          20  0.650000       1.0         0.0  20.802327
حقوق جزا           19  0.315789       1.0         0.0  24.394658